import RiemannHypothesisProject.GuinandWeilFormulaTarget
import RiemannHypothesisProject.GlobalZeroSide
import RiemannHypothesisProject.GuinandWeilConcrete.Sides
import RiemannHypothesisProject.GuinandWeilConcrete.PrimeCutoff
import RiemannHypothesisProject.GuinandWeilConcrete.ResidualCutoff
import RiemannHypothesisProject.GuinandWeilConcrete.ZeroCutoff
import RiemannHypothesisProject.GuinandWeilConcrete.FormulaGap
import RiemannHypothesisProject.GuinandWeilConcrete.ErrorEnvelope
import RiemannHypothesisProject.GuinandWeilConcrete.RestrictedSource
import RiemannHypothesisProject.SchwartzRiemannWeilWeight
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Analysis.SpecialFunctions.Gamma.Deligne
import Mathlib.NumberTheory.ArithmeticFunction.VonMangoldt

/-!
# Concrete Guinand-Weil formula sides facade

This compatibility facade re-exports the focused concrete Guinand-Weil formula
side, cutoff, formula-gap, error-envelope, and restricted-source modules.
-/
