import RiemannHypothesisProject.LanglandsPurityBridge
import Mathlib.Data.Finset.Basic

/-!
# Finite Langlands-style phase toy model

This file gives a tiny checked toy model for the function-field/Langlands
analogy. A finite set of unitary phase heights is enough to prove local RH for
any family of zeroes that is realized by those phases.

This is not a statement about actual zeta zeroes beyond the explicit family
realization hypothesis. Its purpose is to make the purity/phase bridge
concrete in the same style as the finite zero-window examples.
-/

namespace RiemannHypothesisProject

/--
A finite unitary-phase window for a chosen family.

The phases are represented by real heights. The key hypothesis is the explicit
realization field: every nontrivial zeta zero in the family must be one of the
critical-line points attached to those phase heights.
-/
structure FiniteUnitaryPhaseWindowModel (family : Complex -> Prop) where
  phases : Finset Real
  realizes_family_zeroes :
    forall s : Complex, family s -> IsNontrivialZetaZero s ->
      exists t : Real, t ∈ phases ∧ criticalLinePoint t = s

namespace FiniteUnitaryPhaseWindowModel

/-- A finite unitary-phase window gives a local purity/phase model. -/
noncomputable def toLocalPurityPhaseModel
    {family : Complex -> Prop}
    (model : FiniteUnitaryPhaseWindowModel family) :
    LocalPurityPhaseModel family where
  Parameter := {t : Real // t ∈ model.phases}
  phaseHeight t := t.1
  realizes_family_zeroes := by
    intro s hs_family hs_zero
    rcases model.realizes_family_zeroes s hs_family hs_zero with
      ⟨t, ht_phases, ht_realizes⟩
    exact ⟨⟨t, ht_phases⟩, ht_realizes⟩

end FiniteUnitaryPhaseWindowModel

/-- A finite unitary-phase window proves RH on its family. -/
theorem RHOn.of_finiteUnitaryPhaseWindowModel
    {family : Complex -> Prop}
    (model : FiniteUnitaryPhaseWindowModel family) :
    RHOn family :=
  RHOn.of_localPurityPhaseModel model.toLocalPurityPhaseModel

/-- The toy family generated by finitely many pure phase heights. -/
def finitePurePhaseFamily (phases : Finset Real) : Complex -> Prop :=
  fun s => exists t : Real, t ∈ phases ∧ criticalLinePoint t = s

/-- The generated finite phase family has a tautological phase-window model. -/
noncomputable def finitePurePhaseWindowModel
    (phases : Finset Real) :
    FiniteUnitaryPhaseWindowModel (finitePurePhaseFamily phases) where
  phases := phases
  realizes_family_zeroes := by
    intro s hs_family _hs_zero
    exact hs_family

/--
RH holds on the finite family generated by pure phase heights.

This is the toy-model version of the purity principle: once the relevant
zeroes are parametrized by real phase heights, critical-line membership is
formal.
-/
theorem RHOn_finitePurePhaseFamily
    (phases : Finset Real) :
    RHOn (finitePurePhaseFamily phases) :=
  RHOn.of_finiteUnitaryPhaseWindowModel
    (finitePurePhaseWindowModel phases)

end RiemannHypothesisProject
