import Mathlib.Analysis.Calculus.BumpFunction.FiniteDimension
import Mathlib.Analysis.Complex.Liouville
import Mathlib.Analysis.Distribution.TestFunction
import RiemannHypothesisProject.GuinandWeilDensityFormulaBridge
import RiemannHypothesisProject.GuinandWeilTestFunctionTarget
import RiemannHypothesisProject.RiemannWeilShiftedRadius.RealSchwartzSeminorms
import RiemannHypothesisProject.RiemannWeilShiftedRadius.CutoffApproximation
import RiemannHypothesisProject.RiemannWeilShiftedRadius.ZeroArgumentContinuity
import RiemannHypothesisProject.RiemannWeilShiftedRadius.StripGeometry
import RiemannHypothesisProject.RiemannWeilShiftedRadius.TrivialAxisGeometry
import RiemannHypothesisProject.RiemannWeilShiftedRadius.FiniteComponentMajorants
import RiemannHypothesisProject.RiemannWeilShiftedRadius.FiniteComponentZeroArgument.RealFourierTail
import RiemannHypothesisProject.RiemannWeilShiftedRadius.SourceWeightSummability.RealFourierEndpoints
import RiemannHypothesisProject.RiemannWeilShiftedRadius.ProjectWeightEndpoints
import RiemannHypothesisProject.RiemannWeilShiftedRadius.CertificateCore
import RiemannHypothesisProject.RiemannWeilShiftedRadius.DenseSourceCertificates
import RiemannHypothesisProject.RiemannWeilShiftedRadius.FiniteComponentSourceImageCertificates
import RiemannHypothesisProject.RiemannWeilShiftedRadius.CertificateEndpoints
import RiemannHypothesisProject.RiemannWeilShiftedRadius.SourceImageGuardrails
import RiemannHypothesisProject.RiemannWeilAntitoneRadialSplitPSeriesBridge

/-!
# Shifted-radius decay certificate facade

This compatibility facade re-exports the focused shifted-radius p-series
certificate modules split out of the original discovery file.
-/
