import RiemannHypothesisProject.RiemannWeilConcretePublishedCountingPSeriesAssembly

/-!
# Source-formula concrete Riemann-Weil assembly

`RiemannWeilConcretePublishedCountingPSeriesAssembly` starts from concrete
published counting inputs but still asks for an already assembled
`GuinandWeilProjectFormulaPackage`.

This file exposes the source-formula fields directly: a
`GuinandWeilSourceFormulaPackage` plus a normalization bridge to the zero side
generated by the concrete counting and radial p-series data.  This keeps the
future Guinand-Weil proof target visible all the way to the final conditional
RH endpoint.
-/

namespace RiemannHypothesisProject

open ComplexCompactExhaustion

noncomputable section

/--
End-to-end concrete assembly with source-normalized Guinand-Weil formula data
kept explicit.

The fields are the current source-guided analytic work units:

* concrete published `N(T)` counting input;
* antitone radial p-series envelope input;
* source Guinand-Weil formula package;
* normalization bridge from the source zero side to the generated zero side;
* residual-to-Li coefficient bridge;
* residual nonnegativity.
-/
structure RiemannWeilFixedErrorSourceFormulaAnalyticAssembly
    (validFrom : Real) (publishedErrorTerm : Real -> Real) where
  zeroData :
    RiemannWeilFixedErrorPublishedCountingAntitonePSeriesData
      validFrom publishedErrorTerm
  sourcePackage : GuinandWeilSourceFormulaPackage
  normalizationBridge :
    GuinandWeilNormalizationBridge
      sourcePackage.sourceData
      zeroData.toEventualPSeriesEnvelopeZeroData.zeroSide
  liData : AbstractLiCriterionData (fun _ : Complex => True)
  residualToLi :
    FormulaResidualToLiCoefficientBridge
      normalizationBridge.toFormulaIdentityData liData
  residual_nonneg :
    forall f : SchwartzLineTestFunction,
      0 <= normalizationBridge.toFormulaIdentityData.sideData.residualSide f

namespace RiemannWeilFixedErrorSourceFormulaAnalyticAssembly

/--
Build the source-formula concrete assembly directly from split
finite-prefix/tail p-series data whose counting estimate matches the fixed
published source input.
-/
noncomputable def ofSplitPSeriesEnvelopeData
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (publishedCounting :
      FixedErrorExplicitRiemannVonMangoldtSourceInput
        validFrom publishedErrorTerm)
    (splitData : RiemannWeilAntitoneRadialSplitPSeriesEnvelopeData)
    (counting_eq :
      splitData.counting = publishedCounting.toPolynomialZeroCountingEstimate)
    (sourcePackage : GuinandWeilSourceFormulaPackage)
    (normalizationBridge :
      GuinandWeilNormalizationBridge
        sourcePackage.sourceData
        ((RiemannWeilFixedErrorPublishedCountingAntitonePSeriesData.ofSplitPSeriesEnvelopeData
          publishedCounting splitData counting_eq)
          |>.toEventualPSeriesEnvelopeZeroData
          |>.zeroSide))
    (liData : AbstractLiCriterionData (fun _ : Complex => True))
    (residualToLi :
      FormulaResidualToLiCoefficientBridge
        normalizationBridge.toFormulaIdentityData liData)
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= normalizationBridge.toFormulaIdentityData.sideData.residualSide f) :
    RiemannWeilFixedErrorSourceFormulaAnalyticAssembly
      validFrom publishedErrorTerm where
  zeroData :=
    RiemannWeilFixedErrorPublishedCountingAntitonePSeriesData.ofSplitPSeriesEnvelopeData
      publishedCounting splitData counting_eq
  sourcePackage := sourcePackage
  normalizationBridge := normalizationBridge
  liData := liData
  residualToLi := residualToLi
  residual_nonneg := residual_nonneg

/--
Build the source-formula concrete assembly directly from an automatic-prefix
radial target whose counting estimate matches the fixed published source
input.
-/
noncomputable def ofAutomaticPrefixRadialTarget
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (publishedCounting :
      FixedErrorExplicitRiemannVonMangoldtSourceInput
        validFrom publishedErrorTerm)
    (target : RiemannWeilAutomaticPrefixRadialPSeriesTarget)
    (counting_eq :
      target.counting = publishedCounting.toPolynomialZeroCountingEstimate)
    (sourcePackage : GuinandWeilSourceFormulaPackage)
    (normalizationBridge :
      GuinandWeilNormalizationBridge
        sourcePackage.sourceData
        ((RiemannWeilFixedErrorPublishedCountingAntitonePSeriesData.ofAutomaticPrefixRadialTarget
          publishedCounting target counting_eq)
          |>.toEventualPSeriesEnvelopeZeroData
          |>.zeroSide))
    (liData : AbstractLiCriterionData (fun _ : Complex => True))
    (residualToLi :
      FormulaResidualToLiCoefficientBridge
        normalizationBridge.toFormulaIdentityData liData)
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= normalizationBridge.toFormulaIdentityData.sideData.residualSide f) :
    RiemannWeilFixedErrorSourceFormulaAnalyticAssembly
      validFrom publishedErrorTerm where
  zeroData :=
    RiemannWeilFixedErrorPublishedCountingAntitonePSeriesData.ofAutomaticPrefixRadialTarget
      publishedCounting target counting_eq
  sourcePackage := sourcePackage
  normalizationBridge := normalizationBridge
  liData := liData
  residualToLi := residualToLi
  residual_nonneg := residual_nonneg

/-- Assemble the project-level Guinand-Weil formula package from source data. -/
noncomputable def formulaPackage
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (assembly :
      RiemannWeilFixedErrorSourceFormulaAnalyticAssembly
        validFrom publishedErrorTerm) :
    GuinandWeilProjectFormulaPackage
      assembly.zeroData.toEventualPSeriesEnvelopeZeroData.zeroSide where
  sourcePackage := assembly.sourcePackage
  normalizationBridge := assembly.normalizationBridge

/-- Forget the source-formula decomposition and use the concrete published-counting assembly. -/
noncomputable def toFixedErrorPublishedCountingAnalyticAssembly
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (assembly :
      RiemannWeilFixedErrorSourceFormulaAnalyticAssembly
        validFrom publishedErrorTerm) :
    RiemannWeilFixedErrorPublishedCountingAnalyticAssembly
      validFrom publishedErrorTerm where
  zeroData := assembly.zeroData
  formulaPackage := assembly.formulaPackage
  liData := assembly.liData
  residualToLi := assembly.residualToLi
  residual_nonneg := assembly.residual_nonneg

/-- Assemble the final eventual p-series formula-residual input package. -/
noncomputable def toEventualPSeriesFormulaResidualInputData
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (assembly :
      RiemannWeilFixedErrorSourceFormulaAnalyticAssembly
        validFrom publishedErrorTerm) :
    SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaResidualInputData :=
  assembly.toFixedErrorPublishedCountingAnalyticAssembly
    |>.toEventualPSeriesFormulaResidualInputData

/-- Source formula data gives residual continuity for the project-normalized formula. -/
noncomputable def residualContinuityData
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (assembly :
      RiemannWeilFixedErrorSourceFormulaAnalyticAssembly
        validFrom publishedErrorTerm) :
    SchwartzRiemannWeilFormulaResidualContinuityData
      assembly.normalizationBridge.toFormulaIdentityData :=
  assembly.formulaPackage.residualContinuityData

/-- The concrete assembly's project residual side is the source residual side. -/
theorem formulaResidualSide_eq_sourceResidualSide
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (assembly :
      RiemannWeilFixedErrorSourceFormulaAnalyticAssembly
        validFrom publishedErrorTerm)
    (f : SchwartzLineTestFunction) :
    assembly.normalizationBridge.toFormulaIdentityData.sideData.residualSide f =
      assembly.sourcePackage.sourceData.sideData.sourceResidualSide f :=
  assembly.formulaPackage.formulaData_residualSide_eq_sourceResidualSide f

/--
The concrete source-formula assembly's zero side equals the source residual
side after applying the normalization bridge.
-/
theorem zeroSide_eq_sourceResidualSide
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (assembly :
      RiemannWeilFixedErrorSourceFormulaAnalyticAssembly
        validFrom publishedErrorTerm)
    (f : SchwartzLineTestFunction) :
    assembly.zeroData.toEventualPSeriesEnvelopeZeroData.zeroSide.zeroSide f =
      assembly.sourcePackage.sourceData.sideData.sourceResidualSide f :=
  assembly.formulaPackage.explicitFormula_sourceResidualSide f

/-- The residual-nonnegative locus is closed for the source-normalized assembly. -/
theorem residual_nonnegativeSet_closed
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (assembly :
      RiemannWeilFixedErrorSourceFormulaAnalyticAssembly
        validFrom publishedErrorTerm) :
    IsClosed
      (formulaResidualNonnegativeSet
        assembly.normalizationBridge.toFormulaIdentityData) :=
  assembly.formulaPackage.residual_nonnegativeSet_closed

/-- The source-formula assembly proves universal local RH, conditionally. -/
theorem RHOn_univ
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (assembly :
      RiemannWeilFixedErrorSourceFormulaAnalyticAssembly
        validFrom publishedErrorTerm) :
    RHOn (fun _ : Complex => True) :=
  assembly.toFixedErrorPublishedCountingAnalyticAssembly.RHOn_univ

/-- The source-formula assembly proves the project RH statement, conditionally. -/
theorem RHStatement
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (assembly :
      RiemannWeilFixedErrorSourceFormulaAnalyticAssembly
        validFrom publishedErrorTerm) :
    RiemannHypothesisProject.RHStatement :=
  assembly.toFixedErrorPublishedCountingAnalyticAssembly.RHStatement

/-- The source-formula assembly proves Mathlib RH, conditionally. -/
theorem mathlib_RH
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (assembly :
      RiemannWeilFixedErrorSourceFormulaAnalyticAssembly
        validFrom publishedErrorTerm) :
    RiemannHypothesis :=
  assembly.toFixedErrorPublishedCountingAnalyticAssembly.mathlib_RH

end RiemannWeilFixedErrorSourceFormulaAnalyticAssembly

/--
End-to-end concrete assembly with componentwise source-normalized
Guinand-Weil formula data kept explicit.

This is the sharper companion to
`RiemannWeilFixedErrorSourceFormulaAnalyticAssembly`: the normalization bridge
may compare the project zero, prime, pole, and gamma sides separately, and the
resulting componentwise project side data is preserved all the way to the final
formula-residual input package.
-/
structure RiemannWeilFixedErrorComponentwiseSourceFormulaAnalyticAssembly
    (validFrom : Real) (publishedErrorTerm : Real -> Real) where
  zeroData :
    RiemannWeilFixedErrorPublishedCountingAntitonePSeriesData
      validFrom publishedErrorTerm
  sourcePackage : GuinandWeilSourceFormulaPackage
  normalizationBridge :
    GuinandWeilComponentwiseNormalizationBridge
      sourcePackage.sourceData
      zeroData.toEventualPSeriesEnvelopeZeroData.zeroSide
  liData : AbstractLiCriterionData (fun _ : Complex => True)
  residualToLi :
    FormulaResidualToLiCoefficientBridge
      normalizationBridge.toFormulaIdentityData liData
  residual_nonneg :
    forall f : SchwartzLineTestFunction,
      0 <= normalizationBridge.toFormulaIdentityData.sideData.residualSide f

namespace RiemannWeilFixedErrorComponentwiseSourceFormulaAnalyticAssembly

/--
Build the componentwise source-formula concrete assembly directly from split
finite-prefix/tail p-series data whose counting estimate matches the fixed
published source input.
-/
noncomputable def ofSplitPSeriesEnvelopeData
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (publishedCounting :
      FixedErrorExplicitRiemannVonMangoldtSourceInput
        validFrom publishedErrorTerm)
    (splitData : RiemannWeilAntitoneRadialSplitPSeriesEnvelopeData)
    (counting_eq :
      splitData.counting = publishedCounting.toPolynomialZeroCountingEstimate)
    (sourcePackage : GuinandWeilSourceFormulaPackage)
    (normalizationBridge :
      GuinandWeilComponentwiseNormalizationBridge
        sourcePackage.sourceData
        ((RiemannWeilFixedErrorPublishedCountingAntitonePSeriesData.ofSplitPSeriesEnvelopeData
          publishedCounting splitData counting_eq)
          |>.toEventualPSeriesEnvelopeZeroData
          |>.zeroSide))
    (liData : AbstractLiCriterionData (fun _ : Complex => True))
    (residualToLi :
      FormulaResidualToLiCoefficientBridge
        normalizationBridge.toFormulaIdentityData liData)
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= normalizationBridge.toFormulaIdentityData.sideData.residualSide f) :
    RiemannWeilFixedErrorComponentwiseSourceFormulaAnalyticAssembly
      validFrom publishedErrorTerm where
  zeroData :=
    RiemannWeilFixedErrorPublishedCountingAntitonePSeriesData.ofSplitPSeriesEnvelopeData
      publishedCounting splitData counting_eq
  sourcePackage := sourcePackage
  normalizationBridge := normalizationBridge
  liData := liData
  residualToLi := residualToLi
  residual_nonneg := residual_nonneg

/--
Build the componentwise source-formula concrete assembly directly from an
automatic-prefix radial target whose counting estimate matches the fixed
published source input.
-/
noncomputable def ofAutomaticPrefixRadialTarget
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (publishedCounting :
      FixedErrorExplicitRiemannVonMangoldtSourceInput
        validFrom publishedErrorTerm)
    (target : RiemannWeilAutomaticPrefixRadialPSeriesTarget)
    (counting_eq :
      target.counting = publishedCounting.toPolynomialZeroCountingEstimate)
    (sourcePackage : GuinandWeilSourceFormulaPackage)
    (normalizationBridge :
      GuinandWeilComponentwiseNormalizationBridge
        sourcePackage.sourceData
        ((RiemannWeilFixedErrorPublishedCountingAntitonePSeriesData.ofAutomaticPrefixRadialTarget
          publishedCounting target counting_eq)
          |>.toEventualPSeriesEnvelopeZeroData
          |>.zeroSide))
    (liData : AbstractLiCriterionData (fun _ : Complex => True))
    (residualToLi :
      FormulaResidualToLiCoefficientBridge
        normalizationBridge.toFormulaIdentityData liData)
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= normalizationBridge.toFormulaIdentityData.sideData.residualSide f) :
    RiemannWeilFixedErrorComponentwiseSourceFormulaAnalyticAssembly
      validFrom publishedErrorTerm where
  zeroData :=
    RiemannWeilFixedErrorPublishedCountingAntitonePSeriesData.ofAutomaticPrefixRadialTarget
      publishedCounting target counting_eq
  sourcePackage := sourcePackage
  normalizationBridge := normalizationBridge
  liData := liData
  residualToLi := residualToLi
  residual_nonneg := residual_nonneg

/-- Assemble the componentwise project-level Guinand-Weil formula package. -/
noncomputable def formulaPackage
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (assembly :
      RiemannWeilFixedErrorComponentwiseSourceFormulaAnalyticAssembly
        validFrom publishedErrorTerm) :
    GuinandWeilComponentwiseProjectFormulaPackage
      assembly.zeroData.toEventualPSeriesEnvelopeZeroData.zeroSide where
  sourcePackage := assembly.sourcePackage
  normalizationBridge := assembly.normalizationBridge

/-- Formula residual positivity data for the componentwise formula sides. -/
noncomputable def formulaResidualPositivityData
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (assembly :
      RiemannWeilFixedErrorComponentwiseSourceFormulaAnalyticAssembly
        validFrom publishedErrorTerm) :
    SchwartzRiemannWeilFormulaResidualPositivityData
      assembly.normalizationBridge.toFormulaIdentityData :=
  assembly.residualToLi.toFormulaResidualPositivityData
    assembly.residual_nonneg

/-- Assemble the final eventual p-series formula-residual input package. -/
noncomputable def toEventualPSeriesFormulaResidualInputData
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (assembly :
      RiemannWeilFixedErrorComponentwiseSourceFormulaAnalyticAssembly
        validFrom publishedErrorTerm) :
    SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaResidualInputData where
  zeroData := assembly.zeroData.toEventualPSeriesEnvelopeZeroData
  formulaData := assembly.normalizationBridge.toFormulaIdentityData
  formulaResidualData := assembly.formulaResidualPositivityData

/-- Componentwise source formula data gives residual continuity after normalization. -/
noncomputable def residualContinuityData
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (assembly :
      RiemannWeilFixedErrorComponentwiseSourceFormulaAnalyticAssembly
        validFrom publishedErrorTerm) :
    SchwartzRiemannWeilFormulaResidualContinuityData
      assembly.normalizationBridge.toFormulaIdentityData :=
  assembly.formulaPackage.residualContinuityData

/-- The componentwise assembly's project residual side is the source residual side. -/
theorem formulaResidualSide_eq_sourceResidualSide
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (assembly :
      RiemannWeilFixedErrorComponentwiseSourceFormulaAnalyticAssembly
        validFrom publishedErrorTerm)
    (f : SchwartzLineTestFunction) :
    assembly.normalizationBridge.toFormulaIdentityData.sideData.residualSide f =
      assembly.sourcePackage.sourceData.sideData.sourceResidualSide f :=
  assembly.formulaPackage.formulaData_residualSide_eq_sourceResidualSide f

/--
The componentwise concrete source-formula assembly's zero side equals the
source residual side after applying the normalization bridge.
-/
theorem zeroSide_eq_sourceResidualSide
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (assembly :
      RiemannWeilFixedErrorComponentwiseSourceFormulaAnalyticAssembly
        validFrom publishedErrorTerm)
    (f : SchwartzLineTestFunction) :
    assembly.zeroData.toEventualPSeriesEnvelopeZeroData.zeroSide.zeroSide f =
      assembly.sourcePackage.sourceData.sideData.sourceResidualSide f :=
  assembly.formulaPackage.explicitFormula_sourceResidualSide f

/-- The residual-nonnegative locus is closed for the componentwise source assembly. -/
theorem residual_nonnegativeSet_closed
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (assembly :
      RiemannWeilFixedErrorComponentwiseSourceFormulaAnalyticAssembly
        validFrom publishedErrorTerm) :
    IsClosed
      (formulaResidualNonnegativeSet
        assembly.normalizationBridge.toFormulaIdentityData) :=
  assembly.formulaPackage.residual_nonnegativeSet_closed

/-- The componentwise source-formula assembly proves universal local RH, conditionally. -/
theorem RHOn_univ
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (assembly :
      RiemannWeilFixedErrorComponentwiseSourceFormulaAnalyticAssembly
        validFrom publishedErrorTerm) :
    RHOn (fun _ : Complex => True) :=
  assembly.toEventualPSeriesFormulaResidualInputData.RHOn_univ

/-- The componentwise source-formula assembly proves the project RH statement, conditionally. -/
theorem RHStatement
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (assembly :
      RiemannWeilFixedErrorComponentwiseSourceFormulaAnalyticAssembly
        validFrom publishedErrorTerm) :
    RiemannHypothesisProject.RHStatement :=
  assembly.toEventualPSeriesFormulaResidualInputData.RHStatement

/-- The componentwise source-formula assembly proves Mathlib RH, conditionally. -/
theorem mathlib_RH
    {validFrom : Real} {publishedErrorTerm : Real -> Real}
    (assembly :
      RiemannWeilFixedErrorComponentwiseSourceFormulaAnalyticAssembly
        validFrom publishedErrorTerm) :
    RiemannHypothesis :=
  assembly.toEventualPSeriesFormulaResidualInputData.mathlib_RH

end RiemannWeilFixedErrorComponentwiseSourceFormulaAnalyticAssembly

/-- Bellotti-Wong specialization with source Guinand-Weil formula fields exposed. -/
abbrev RiemannWeilBellottiWongSourceFormulaAnalyticAssembly :=
  RiemannWeilFixedErrorSourceFormulaAnalyticAssembly
    bellottiWongValidFrom bellottiWongErrorTerm

/-- Bellotti-Wong specialization with componentwise source Guinand-Weil formula fields exposed. -/
abbrev RiemannWeilBellottiWongComponentwiseSourceFormulaAnalyticAssembly :=
  RiemannWeilFixedErrorComponentwiseSourceFormulaAnalyticAssembly
    bellottiWongValidFrom bellottiWongErrorTerm

/--
Hasanalizade-Shen-Wong specialization with source Guinand-Weil formula fields
exposed and the validity threshold still explicit.
-/
abbrev RiemannWeilHasanalizadeShenWongSourceFormulaAnalyticAssembly
    (validFrom : Real) :=
  RiemannWeilFixedErrorSourceFormulaAnalyticAssembly
    validFrom hasanalizadeShenWongErrorTerm

/--
Hasanalizade-Shen-Wong specialization with componentwise source Guinand-Weil
formula fields exposed and the validity threshold still explicit.
-/
abbrev RiemannWeilHasanalizadeShenWongComponentwiseSourceFormulaAnalyticAssembly
    (validFrom : Real) :=
  RiemannWeilFixedErrorComponentwiseSourceFormulaAnalyticAssembly
    validFrom hasanalizadeShenWongErrorTerm

/--
Bellotti-Wong source-formula assembly from the preferred exact-source package
and the preferred cutoff-2 exact-norm clipped p-series estimate.  The
remaining fields are exactly the source Guinand-Weil formula package, its
normalization to the generated zero side, the Li bridge, and residual
positivity.
-/
noncomputable def RiemannWeilBellottiWongSourceFormulaAnalyticAssembly.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelf
    (sourceData : BellottiWongExactHeightWindowConjugationSourceData)
    (system : SchwartzRiemannWeilExtensionSystem)
    (constant : SchwartzLineTestFunction -> Real)
    (decayExponent : Real)
    (constant_nonneg :
      forall f : SchwartzLineTestFunction, 0 <= constant f)
    (decay_margin : (3 : Real) < decayExponent)
    (extension_norm_le_clippedRadialBound :
      forall (f : SchwartzLineTestFunction) (z : Complex),
        norm (system.extension f z) <=
          RiemannWeilAntitoneRadialPSeriesEnvelopeData.clippedPSeriesRadialBound
            constant decayExponent f (norm z))
    (sourcePackage : GuinandWeilSourceFormulaPackage)
    (normalizationBridge :
      GuinandWeilNormalizationBridge
        sourcePackage.sourceData
        ((RiemannWeilBellottiWongAntitonePSeriesData.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelf
            sourceData system constant decayExponent constant_nonneg
            decay_margin extension_norm_le_clippedRadialBound)
          |>.toEventualPSeriesEnvelopeZeroData
          |>.zeroSide))
    (liData : AbstractLiCriterionData (fun _ : Complex => True))
    (residualToLi :
      FormulaResidualToLiCoefficientBridge
        normalizationBridge.toFormulaIdentityData liData)
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= normalizationBridge.toFormulaIdentityData.sideData.residualSide f) :
    RiemannWeilBellottiWongSourceFormulaAnalyticAssembly where
  zeroData :=
    RiemannWeilBellottiWongAntitonePSeriesData.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelf
      sourceData system constant decayExponent constant_nonneg decay_margin
      extension_norm_le_clippedRadialBound
  sourcePackage := sourcePackage
  normalizationBridge := normalizationBridge
  liData := liData
  residualToLi := residualToLi
  residual_nonneg := residual_nonneg

/--
Bellotti-Wong source-formula assembly from the preferred exact-source package
and a cutoff-2 exact-norm shifted-radius p-series estimate.  The remaining
fields are the source Guinand-Weil formula package, normalization, Li bridge,
and residual positivity.
-/
noncomputable def RiemannWeilBellottiWongSourceFormulaAnalyticAssembly.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelfOfShiftedRadius
    (sourceData : BellottiWongExactHeightWindowConjugationSourceData)
    (system : SchwartzRiemannWeilExtensionSystem)
    (constant : SchwartzLineTestFunction -> Real)
    (decayExponent : Real)
    (constant_nonneg :
      forall f : SchwartzLineTestFunction, 0 <= constant f)
    (decay_margin : (3 : Real) < decayExponent)
    (extension_norm_le_shiftedRadialBound :
      forall (f : SchwartzLineTestFunction) (z : Complex),
        norm (system.extension f z) <=
          constant f * (1 / (norm z + 2) ^ decayExponent))
    (sourcePackage : GuinandWeilSourceFormulaPackage)
    (normalizationBridge :
      GuinandWeilNormalizationBridge
        sourcePackage.sourceData
        ((RiemannWeilBellottiWongAntitonePSeriesData.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelfOfShiftedRadius
            sourceData system constant decayExponent constant_nonneg
            decay_margin extension_norm_le_shiftedRadialBound)
          |>.toEventualPSeriesEnvelopeZeroData
          |>.zeroSide))
    (liData : AbstractLiCriterionData (fun _ : Complex => True))
    (residualToLi :
      FormulaResidualToLiCoefficientBridge
        normalizationBridge.toFormulaIdentityData liData)
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= normalizationBridge.toFormulaIdentityData.sideData.residualSide f) :
    RiemannWeilBellottiWongSourceFormulaAnalyticAssembly where
  zeroData :=
    RiemannWeilBellottiWongAntitonePSeriesData.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelfOfShiftedRadius
      sourceData system constant decayExponent constant_nonneg decay_margin
      extension_norm_le_shiftedRadialBound
  sourcePackage := sourcePackage
  normalizationBridge := normalizationBridge
  liData := liData
  residualToLi := residualToLi
  residual_nonneg := residual_nonneg

/--
Bellotti-Wong source-formula assembly from the exact source's cumulative count
and a cutoff-2 exact-norm shifted-radius p-series estimate.  The remaining
fields are the source Guinand-Weil formula package, normalization, Li bridge,
and residual positivity.
-/
noncomputable def RiemannWeilBellottiWongSourceFormulaAnalyticAssembly.ofExactSourceCumulativeCutoffTwoShiftedRadiusExactNormSelf
    (sourceData : BellottiWongExactHeightWindowConjugationSourceData)
    (system : SchwartzRiemannWeilExtensionSystem)
    (constant : SchwartzLineTestFunction -> Real)
    (decayExponent : Real)
    (constant_nonneg :
      forall f : SchwartzLineTestFunction, 0 <= constant f)
    (decay_margin : (3 : Real) < decayExponent)
    (extension_norm_le_shiftedRadialBound :
      forall (f : SchwartzLineTestFunction) (z : Complex),
        norm (system.extension f z) <=
          constant f * (1 / (norm z + 2) ^ decayExponent))
    (sourcePackage : GuinandWeilSourceFormulaPackage)
    (normalizationBridge :
      GuinandWeilNormalizationBridge
        sourcePackage.sourceData
        ((RiemannWeilBellottiWongAntitonePSeriesData.ofExactSourceCumulativeCutoffTwoShiftedRadiusExactNormSelf
            sourceData system constant decayExponent constant_nonneg
            decay_margin extension_norm_le_shiftedRadialBound)
          |>.toEventualPSeriesEnvelopeZeroData
          |>.zeroSide))
    (liData : AbstractLiCriterionData (fun _ : Complex => True))
    (residualToLi :
      FormulaResidualToLiCoefficientBridge
        normalizationBridge.toFormulaIdentityData liData)
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= normalizationBridge.toFormulaIdentityData.sideData.residualSide f) :
    RiemannWeilBellottiWongSourceFormulaAnalyticAssembly where
  zeroData :=
    RiemannWeilBellottiWongAntitonePSeriesData.ofExactSourceCumulativeCutoffTwoShiftedRadiusExactNormSelf
      sourceData system constant decayExponent constant_nonneg decay_margin
      extension_norm_le_shiftedRadialBound
  sourcePackage := sourcePackage
  normalizationBridge := normalizationBridge
  liData := liData
  residualToLi := residualToLi
  residual_nonneg := residual_nonneg

/--
Bellotti-Wong componentwise source-formula assembly from the preferred
exact-source package and the preferred cutoff-2 exact-norm clipped p-series
estimate.
-/
noncomputable def RiemannWeilBellottiWongComponentwiseSourceFormulaAnalyticAssembly.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelf
    (sourceData : BellottiWongExactHeightWindowConjugationSourceData)
    (system : SchwartzRiemannWeilExtensionSystem)
    (constant : SchwartzLineTestFunction -> Real)
    (decayExponent : Real)
    (constant_nonneg :
      forall f : SchwartzLineTestFunction, 0 <= constant f)
    (decay_margin : (3 : Real) < decayExponent)
    (extension_norm_le_clippedRadialBound :
      forall (f : SchwartzLineTestFunction) (z : Complex),
        norm (system.extension f z) <=
          RiemannWeilAntitoneRadialPSeriesEnvelopeData.clippedPSeriesRadialBound
            constant decayExponent f (norm z))
    (sourcePackage : GuinandWeilSourceFormulaPackage)
    (normalizationBridge :
      GuinandWeilComponentwiseNormalizationBridge
        sourcePackage.sourceData
        ((RiemannWeilBellottiWongAntitonePSeriesData.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelf
            sourceData system constant decayExponent constant_nonneg
            decay_margin extension_norm_le_clippedRadialBound)
          |>.toEventualPSeriesEnvelopeZeroData
          |>.zeroSide))
    (liData : AbstractLiCriterionData (fun _ : Complex => True))
    (residualToLi :
      FormulaResidualToLiCoefficientBridge
        normalizationBridge.toFormulaIdentityData liData)
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= normalizationBridge.toFormulaIdentityData.sideData.residualSide f) :
    RiemannWeilBellottiWongComponentwiseSourceFormulaAnalyticAssembly where
  zeroData :=
    RiemannWeilBellottiWongAntitonePSeriesData.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelf
      sourceData system constant decayExponent constant_nonneg decay_margin
      extension_norm_le_clippedRadialBound
  sourcePackage := sourcePackage
  normalizationBridge := normalizationBridge
  liData := liData
  residualToLi := residualToLi
  residual_nonneg := residual_nonneg

/--
Bellotti-Wong componentwise source-formula assembly from the preferred
exact-source package and a cutoff-2 exact-norm shifted-radius p-series
estimate.
-/
noncomputable def RiemannWeilBellottiWongComponentwiseSourceFormulaAnalyticAssembly.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelfOfShiftedRadius
    (sourceData : BellottiWongExactHeightWindowConjugationSourceData)
    (system : SchwartzRiemannWeilExtensionSystem)
    (constant : SchwartzLineTestFunction -> Real)
    (decayExponent : Real)
    (constant_nonneg :
      forall f : SchwartzLineTestFunction, 0 <= constant f)
    (decay_margin : (3 : Real) < decayExponent)
    (extension_norm_le_shiftedRadialBound :
      forall (f : SchwartzLineTestFunction) (z : Complex),
        norm (system.extension f z) <=
          constant f * (1 / (norm z + 2) ^ decayExponent))
    (sourcePackage : GuinandWeilSourceFormulaPackage)
    (normalizationBridge :
      GuinandWeilComponentwiseNormalizationBridge
        sourcePackage.sourceData
        ((RiemannWeilBellottiWongAntitonePSeriesData.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelfOfShiftedRadius
            sourceData system constant decayExponent constant_nonneg
            decay_margin extension_norm_le_shiftedRadialBound)
          |>.toEventualPSeriesEnvelopeZeroData
          |>.zeroSide))
    (liData : AbstractLiCriterionData (fun _ : Complex => True))
    (residualToLi :
      FormulaResidualToLiCoefficientBridge
        normalizationBridge.toFormulaIdentityData liData)
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= normalizationBridge.toFormulaIdentityData.sideData.residualSide f) :
    RiemannWeilBellottiWongComponentwiseSourceFormulaAnalyticAssembly where
  zeroData :=
    RiemannWeilBellottiWongAntitonePSeriesData.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelfOfShiftedRadius
      sourceData system constant decayExponent constant_nonneg decay_margin
      extension_norm_le_shiftedRadialBound
  sourcePackage := sourcePackage
  normalizationBridge := normalizationBridge
  liData := liData
  residualToLi := residualToLi
  residual_nonneg := residual_nonneg

/--
Bellotti-Wong componentwise source-formula assembly from the exact source's
cumulative count and a cutoff-2 exact-norm shifted-radius p-series estimate.
-/
noncomputable def RiemannWeilBellottiWongComponentwiseSourceFormulaAnalyticAssembly.ofExactSourceCumulativeCutoffTwoShiftedRadiusExactNormSelf
    (sourceData : BellottiWongExactHeightWindowConjugationSourceData)
    (system : SchwartzRiemannWeilExtensionSystem)
    (constant : SchwartzLineTestFunction -> Real)
    (decayExponent : Real)
    (constant_nonneg :
      forall f : SchwartzLineTestFunction, 0 <= constant f)
    (decay_margin : (3 : Real) < decayExponent)
    (extension_norm_le_shiftedRadialBound :
      forall (f : SchwartzLineTestFunction) (z : Complex),
        norm (system.extension f z) <=
          constant f * (1 / (norm z + 2) ^ decayExponent))
    (sourcePackage : GuinandWeilSourceFormulaPackage)
    (normalizationBridge :
      GuinandWeilComponentwiseNormalizationBridge
        sourcePackage.sourceData
        ((RiemannWeilBellottiWongAntitonePSeriesData.ofExactSourceCumulativeCutoffTwoShiftedRadiusExactNormSelf
            sourceData system constant decayExponent constant_nonneg
            decay_margin extension_norm_le_shiftedRadialBound)
          |>.toEventualPSeriesEnvelopeZeroData
          |>.zeroSide))
    (liData : AbstractLiCriterionData (fun _ : Complex => True))
    (residualToLi :
      FormulaResidualToLiCoefficientBridge
        normalizationBridge.toFormulaIdentityData liData)
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= normalizationBridge.toFormulaIdentityData.sideData.residualSide f) :
    RiemannWeilBellottiWongComponentwiseSourceFormulaAnalyticAssembly where
  zeroData :=
    RiemannWeilBellottiWongAntitonePSeriesData.ofExactSourceCumulativeCutoffTwoShiftedRadiusExactNormSelf
      sourceData system constant decayExponent constant_nonneg decay_margin
      extension_norm_le_shiftedRadialBound
  sourcePackage := sourcePackage
  normalizationBridge := normalizationBridge
  liData := liData
  residualToLi := residualToLi
  residual_nonneg := residual_nonneg

/--
HSW source-formula assembly from the preferred exact-source package and the
preferred cutoff-2 exact-norm clipped p-series estimate.  The exact-source
package supplies the cutoff/growth counting data; the real analytic fields
remain explicit.
-/
noncomputable def RiemannWeilHasanalizadeShenWongSourceFormulaAnalyticAssembly.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelf
    {validFrom : Real}
    (sourceData :
      HasanalizadeShenWongExactHeightWindowConjugationSourceData validFrom)
    (system : SchwartzRiemannWeilExtensionSystem)
    (constant : SchwartzLineTestFunction -> Real)
    (decayExponent : Real)
    (constant_nonneg :
      forall f : SchwartzLineTestFunction, 0 <= constant f)
    (decay_margin : (3 : Real) < decayExponent)
    (extension_norm_le_clippedRadialBound :
      forall (f : SchwartzLineTestFunction) (z : Complex),
        norm (system.extension f z) <=
          RiemannWeilAntitoneRadialPSeriesEnvelopeData.clippedPSeriesRadialBound
            constant decayExponent f (norm z))
    (sourcePackage : GuinandWeilSourceFormulaPackage)
    (normalizationBridge :
      GuinandWeilNormalizationBridge
        sourcePackage.sourceData
        ((RiemannWeilHasanalizadeShenWongAntitonePSeriesData.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelf
            sourceData system constant decayExponent constant_nonneg
            decay_margin extension_norm_le_clippedRadialBound)
          |>.toEventualPSeriesEnvelopeZeroData
          |>.zeroSide))
    (liData : AbstractLiCriterionData (fun _ : Complex => True))
    (residualToLi :
      FormulaResidualToLiCoefficientBridge
        normalizationBridge.toFormulaIdentityData liData)
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= normalizationBridge.toFormulaIdentityData.sideData.residualSide f) :
    RiemannWeilHasanalizadeShenWongSourceFormulaAnalyticAssembly validFrom where
  zeroData :=
    RiemannWeilHasanalizadeShenWongAntitonePSeriesData.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelf
      sourceData system constant decayExponent constant_nonneg decay_margin
      extension_norm_le_clippedRadialBound
  sourcePackage := sourcePackage
  normalizationBridge := normalizationBridge
  liData := liData
  residualToLi := residualToLi
  residual_nonneg := residual_nonneg

/--
HSW source-formula assembly from the preferred exact-source package and a
cutoff-2 exact-norm shifted-radius p-series estimate.  The source formula,
normalization, Li bridge, and residual positivity fields remain explicit.
-/
noncomputable def RiemannWeilHasanalizadeShenWongSourceFormulaAnalyticAssembly.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelfOfShiftedRadius
    {validFrom : Real}
    (sourceData :
      HasanalizadeShenWongExactHeightWindowConjugationSourceData validFrom)
    (system : SchwartzRiemannWeilExtensionSystem)
    (constant : SchwartzLineTestFunction -> Real)
    (decayExponent : Real)
    (constant_nonneg :
      forall f : SchwartzLineTestFunction, 0 <= constant f)
    (decay_margin : (3 : Real) < decayExponent)
    (extension_norm_le_shiftedRadialBound :
      forall (f : SchwartzLineTestFunction) (z : Complex),
        norm (system.extension f z) <=
          constant f * (1 / (norm z + 2) ^ decayExponent))
    (sourcePackage : GuinandWeilSourceFormulaPackage)
    (normalizationBridge :
      GuinandWeilNormalizationBridge
        sourcePackage.sourceData
        ((RiemannWeilHasanalizadeShenWongAntitonePSeriesData.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelfOfShiftedRadius
            sourceData system constant decayExponent constant_nonneg
            decay_margin extension_norm_le_shiftedRadialBound)
          |>.toEventualPSeriesEnvelopeZeroData
          |>.zeroSide))
    (liData : AbstractLiCriterionData (fun _ : Complex => True))
    (residualToLi :
      FormulaResidualToLiCoefficientBridge
        normalizationBridge.toFormulaIdentityData liData)
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= normalizationBridge.toFormulaIdentityData.sideData.residualSide f) :
    RiemannWeilHasanalizadeShenWongSourceFormulaAnalyticAssembly validFrom where
  zeroData :=
    RiemannWeilHasanalizadeShenWongAntitonePSeriesData.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelfOfShiftedRadius
      sourceData system constant decayExponent constant_nonneg decay_margin
      extension_norm_le_shiftedRadialBound
  sourcePackage := sourcePackage
  normalizationBridge := normalizationBridge
  liData := liData
  residualToLi := residualToLi
  residual_nonneg := residual_nonneg

/--
HSW source-formula assembly from the exact source's cumulative count and a
cutoff-2 exact-norm shifted-radius p-series estimate.  The source formula,
normalization, Li bridge, and residual positivity fields remain explicit.
-/
noncomputable def RiemannWeilHasanalizadeShenWongSourceFormulaAnalyticAssembly.ofExactSourceCumulativeCutoffTwoShiftedRadiusExactNormSelf
    {validFrom : Real}
    (sourceData :
      HasanalizadeShenWongExactHeightWindowConjugationSourceData validFrom)
    (system : SchwartzRiemannWeilExtensionSystem)
    (constant : SchwartzLineTestFunction -> Real)
    (decayExponent : Real)
    (constant_nonneg :
      forall f : SchwartzLineTestFunction, 0 <= constant f)
    (decay_margin : (3 : Real) < decayExponent)
    (extension_norm_le_shiftedRadialBound :
      forall (f : SchwartzLineTestFunction) (z : Complex),
        norm (system.extension f z) <=
          constant f * (1 / (norm z + 2) ^ decayExponent))
    (sourcePackage : GuinandWeilSourceFormulaPackage)
    (normalizationBridge :
      GuinandWeilNormalizationBridge
        sourcePackage.sourceData
        ((RiemannWeilHasanalizadeShenWongAntitonePSeriesData.ofExactSourceCumulativeCutoffTwoShiftedRadiusExactNormSelf
            sourceData system constant decayExponent constant_nonneg
            decay_margin extension_norm_le_shiftedRadialBound)
          |>.toEventualPSeriesEnvelopeZeroData
          |>.zeroSide))
    (liData : AbstractLiCriterionData (fun _ : Complex => True))
    (residualToLi :
      FormulaResidualToLiCoefficientBridge
        normalizationBridge.toFormulaIdentityData liData)
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= normalizationBridge.toFormulaIdentityData.sideData.residualSide f) :
    RiemannWeilHasanalizadeShenWongSourceFormulaAnalyticAssembly validFrom where
  zeroData :=
    RiemannWeilHasanalizadeShenWongAntitonePSeriesData.ofExactSourceCumulativeCutoffTwoShiftedRadiusExactNormSelf
      sourceData system constant decayExponent constant_nonneg decay_margin
      extension_norm_le_shiftedRadialBound
  sourcePackage := sourcePackage
  normalizationBridge := normalizationBridge
  liData := liData
  residualToLi := residualToLi
  residual_nonneg := residual_nonneg

/--
HSW componentwise source-formula assembly from the preferred exact-source
package and the preferred cutoff-2 exact-norm clipped p-series estimate.
-/
noncomputable def RiemannWeilHasanalizadeShenWongComponentwiseSourceFormulaAnalyticAssembly.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelf
    {validFrom : Real}
    (sourceData :
      HasanalizadeShenWongExactHeightWindowConjugationSourceData validFrom)
    (system : SchwartzRiemannWeilExtensionSystem)
    (constant : SchwartzLineTestFunction -> Real)
    (decayExponent : Real)
    (constant_nonneg :
      forall f : SchwartzLineTestFunction, 0 <= constant f)
    (decay_margin : (3 : Real) < decayExponent)
    (extension_norm_le_clippedRadialBound :
      forall (f : SchwartzLineTestFunction) (z : Complex),
        norm (system.extension f z) <=
          RiemannWeilAntitoneRadialPSeriesEnvelopeData.clippedPSeriesRadialBound
            constant decayExponent f (norm z))
    (sourcePackage : GuinandWeilSourceFormulaPackage)
    (normalizationBridge :
      GuinandWeilComponentwiseNormalizationBridge
        sourcePackage.sourceData
        ((RiemannWeilHasanalizadeShenWongAntitonePSeriesData.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelf
            sourceData system constant decayExponent constant_nonneg
            decay_margin extension_norm_le_clippedRadialBound)
          |>.toEventualPSeriesEnvelopeZeroData
          |>.zeroSide))
    (liData : AbstractLiCriterionData (fun _ : Complex => True))
    (residualToLi :
      FormulaResidualToLiCoefficientBridge
        normalizationBridge.toFormulaIdentityData liData)
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= normalizationBridge.toFormulaIdentityData.sideData.residualSide f) :
    RiemannWeilHasanalizadeShenWongComponentwiseSourceFormulaAnalyticAssembly
      validFrom where
  zeroData :=
    RiemannWeilHasanalizadeShenWongAntitonePSeriesData.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelf
      sourceData system constant decayExponent constant_nonneg decay_margin
      extension_norm_le_clippedRadialBound
  sourcePackage := sourcePackage
  normalizationBridge := normalizationBridge
  liData := liData
  residualToLi := residualToLi
  residual_nonneg := residual_nonneg

/--
HSW componentwise source-formula assembly from the preferred exact-source
package and a cutoff-2 exact-norm shifted-radius p-series estimate.
-/
noncomputable def RiemannWeilHasanalizadeShenWongComponentwiseSourceFormulaAnalyticAssembly.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelfOfShiftedRadius
    {validFrom : Real}
    (sourceData :
      HasanalizadeShenWongExactHeightWindowConjugationSourceData validFrom)
    (system : SchwartzRiemannWeilExtensionSystem)
    (constant : SchwartzLineTestFunction -> Real)
    (decayExponent : Real)
    (constant_nonneg :
      forall f : SchwartzLineTestFunction, 0 <= constant f)
    (decay_margin : (3 : Real) < decayExponent)
    (extension_norm_le_shiftedRadialBound :
      forall (f : SchwartzLineTestFunction) (z : Complex),
        norm (system.extension f z) <=
          constant f * (1 / (norm z + 2) ^ decayExponent))
    (sourcePackage : GuinandWeilSourceFormulaPackage)
    (normalizationBridge :
      GuinandWeilComponentwiseNormalizationBridge
        sourcePackage.sourceData
        ((RiemannWeilHasanalizadeShenWongAntitonePSeriesData.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelfOfShiftedRadius
            sourceData system constant decayExponent constant_nonneg
            decay_margin extension_norm_le_shiftedRadialBound)
          |>.toEventualPSeriesEnvelopeZeroData
          |>.zeroSide))
    (liData : AbstractLiCriterionData (fun _ : Complex => True))
    (residualToLi :
      FormulaResidualToLiCoefficientBridge
        normalizationBridge.toFormulaIdentityData liData)
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= normalizationBridge.toFormulaIdentityData.sideData.residualSide f) :
    RiemannWeilHasanalizadeShenWongComponentwiseSourceFormulaAnalyticAssembly
      validFrom where
  zeroData :=
    RiemannWeilHasanalizadeShenWongAntitonePSeriesData.ofExactSourceCutoffTwoClippedPSeriesRadialMajorantExactNormSelfOfShiftedRadius
      sourceData system constant decayExponent constant_nonneg decay_margin
      extension_norm_le_shiftedRadialBound
  sourcePackage := sourcePackage
  normalizationBridge := normalizationBridge
  liData := liData
  residualToLi := residualToLi
  residual_nonneg := residual_nonneg

/--
HSW componentwise source-formula assembly from the exact source's cumulative
count and a cutoff-2 exact-norm shifted-radius p-series estimate.
-/
noncomputable def RiemannWeilHasanalizadeShenWongComponentwiseSourceFormulaAnalyticAssembly.ofExactSourceCumulativeCutoffTwoShiftedRadiusExactNormSelf
    {validFrom : Real}
    (sourceData :
      HasanalizadeShenWongExactHeightWindowConjugationSourceData validFrom)
    (system : SchwartzRiemannWeilExtensionSystem)
    (constant : SchwartzLineTestFunction -> Real)
    (decayExponent : Real)
    (constant_nonneg :
      forall f : SchwartzLineTestFunction, 0 <= constant f)
    (decay_margin : (3 : Real) < decayExponent)
    (extension_norm_le_shiftedRadialBound :
      forall (f : SchwartzLineTestFunction) (z : Complex),
        norm (system.extension f z) <=
          constant f * (1 / (norm z + 2) ^ decayExponent))
    (sourcePackage : GuinandWeilSourceFormulaPackage)
    (normalizationBridge :
      GuinandWeilComponentwiseNormalizationBridge
        sourcePackage.sourceData
        ((RiemannWeilHasanalizadeShenWongAntitonePSeriesData.ofExactSourceCumulativeCutoffTwoShiftedRadiusExactNormSelf
            sourceData system constant decayExponent constant_nonneg
            decay_margin extension_norm_le_shiftedRadialBound)
          |>.toEventualPSeriesEnvelopeZeroData
          |>.zeroSide))
    (liData : AbstractLiCriterionData (fun _ : Complex => True))
    (residualToLi :
      FormulaResidualToLiCoefficientBridge
        normalizationBridge.toFormulaIdentityData liData)
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= normalizationBridge.toFormulaIdentityData.sideData.residualSide f) :
    RiemannWeilHasanalizadeShenWongComponentwiseSourceFormulaAnalyticAssembly validFrom where
  zeroData :=
    RiemannWeilHasanalizadeShenWongAntitonePSeriesData.ofExactSourceCumulativeCutoffTwoShiftedRadiusExactNormSelf
      sourceData system constant decayExponent constant_nonneg decay_margin
      extension_norm_le_shiftedRadialBound
  sourcePackage := sourcePackage
  normalizationBridge := normalizationBridge
  liData := liData
  residualToLi := residualToLi
  residual_nonneg := residual_nonneg

end

end RiemannHypothesisProject
