import RiemannHypothesisProject.SchwartzRiemannWeilExtensionProfile
import RiemannHypothesisProject.SchwartzRiemannWeilTailWorkPackages

/-!
# Profiled tail-generated Riemann-Weil work packages

The extension-profile layer turns complex-analytic envelope and shell-decay
data into the separated tail estimate used by the tail work-package endpoint.
This module keeps that profile visible in the work packages themselves.

It provides profiled zero, explicit-formula, and positivity packages. The final
positivity package forgets to the tail work packages, then inherits the global
criterion and RH consequences from the existing endpoint pipeline.
-/

namespace RiemannHypothesisProject

open Filter
open scoped Topology

/-- Zero-side data produced by a profiled separated tail estimate. -/
structure SchwartzRiemannWeilProfiledTailZeroData where
  exhaustion : ComplexCompactExhaustion
  system : SchwartzRiemannWeilExtensionSystem
  profiledTailEstimate :
    SchwartzRiemannWeilProfiledSeparatedTailEstimate exhaustion system

namespace SchwartzRiemannWeilProfiledTailZeroData

/-- Lift generic tail zero data to profiled zero data using the conservative profile. -/
noncomputable def ofTailZeroData
    (zeroData : SchwartzRiemannWeilTailZeroData) :
    SchwartzRiemannWeilProfiledTailZeroData where
  exhaustion := zeroData.exhaustion
  system := zeroData.system
  profiledTailEstimate :=
    SchwartzRiemannWeilProfiledSeparatedTailEstimate.ofSeparatedPolynomialDecayEstimate
      zeroData.tailEstimate

/-- Forget profiled zero data to the tail zero-data package. -/
noncomputable def toTailZeroData
    (zeroData : SchwartzRiemannWeilProfiledTailZeroData) :
    SchwartzRiemannWeilTailZeroData where
  exhaustion := zeroData.exhaustion
  system := zeroData.system
  tailEstimate :=
    zeroData.profiledTailEstimate.toSeparatedPolynomialDecayEstimate

/-- The zero side generated by the profiled tail estimate. -/
noncomputable def zeroSide
    (zeroData : SchwartzRiemannWeilProfiledTailZeroData) :
    SchwartzRiemannWeilZeroSide :=
  zeroData.profiledTailEstimate.toZeroSide

/-- The profiled zero side agrees with the tail-work-package zero side. -/
theorem zeroSide_eq_tailZeroData_zeroSide
    (zeroData : SchwartzRiemannWeilProfiledTailZeroData) :
    zeroData.zeroSide = zeroData.toTailZeroData.zeroSide :=
  rfl

/-- Lifting generic zero data preserves the global zero-side value. -/
theorem ofTailZeroData_zeroSide_eq
    (zeroData : SchwartzRiemannWeilTailZeroData)
    (f : SchwartzLineTestFunction) :
    (ofTailZeroData zeroData).zeroSide.zeroSide f =
      zeroData.zeroSide.zeroSide f := by
  unfold SchwartzRiemannWeilProfiledTailZeroData.zeroSide
    SchwartzRiemannWeilTailZeroData.zeroSide
    SchwartzRiemannWeilZeroSide.zeroSide
    SchwartzRiemannWeilZeroSide.toGlobalZetaZeroSide
    GlobalZetaZeroSide.zeroSide
  apply tsum_congr
  intro rho
  trans zeroData.system.weight f rho
  · exact
      (SchwartzRiemannWeilProfiledSeparatedTailEstimate.ofSeparatedPolynomialDecayEstimate
        zeroData.tailEstimate).toZeroSide_weight f rho
  · exact (zeroData.tailEstimate.toZeroSide_weight f rho).symm

/-- The profiled tail-generated zero side uses the candidate extension-system weight. -/
theorem zeroSide_weight
    (zeroData : SchwartzRiemannWeilProfiledTailZeroData)
    (f : SchwartzLineTestFunction)
    (rho : ZetaZeroSubtype) :
    zeroData.zeroSide.weight f rho = zeroData.system.weight f rho :=
  zeroData.profiledTailEstimate.toZeroSide_weight f rho

/-- Compact-exhaustion sums converge for the profiled tail-generated zero side. -/
theorem tendsto_windowZeroSide
    (zeroData : SchwartzRiemannWeilProfiledTailZeroData)
    (windowExhaustion : ComplexCompactExhaustion)
    (f : SchwartzLineTestFunction) :
    Tendsto
      (fun n : Nat => zeroData.zeroSide.windowZeroSide windowExhaustion n f)
      atTop (nhds (zeroData.zeroSide.zeroSide f)) :=
  zeroData.profiledTailEstimate.tendsto_windowZeroSide windowExhaustion f

end SchwartzRiemannWeilProfiledTailZeroData

/-- Explicit-formula data relative to a profiled tail-generated zero side. -/
structure SchwartzRiemannWeilProfiledTailExplicitFormulaData
    (zeroData : SchwartzRiemannWeilProfiledTailZeroData) where
  primeSide : SchwartzLineTestFunction -> Real
  poleSide : SchwartzLineTestFunction -> Real
  gammaSide : SchwartzLineTestFunction -> Real
  explicitFormula :
    forall f : SchwartzLineTestFunction,
      zeroData.zeroSide.zeroSide f =
        primeSide f + poleSide f + gammaSide f

namespace SchwartzRiemannWeilProfiledTailExplicitFormulaData

/-- Build profiled explicit-formula data from packaged formula-side identity data. -/
noncomputable def ofFormulaIdentityData
    {zeroData : SchwartzRiemannWeilProfiledTailZeroData}
    (formulaData :
      SchwartzRiemannWeilFormulaIdentityData zeroData.zeroSide) :
    SchwartzRiemannWeilProfiledTailExplicitFormulaData zeroData where
  primeSide := formulaData.sideData.primeSide
  poleSide := formulaData.sideData.poleSide
  gammaSide := formulaData.sideData.gammaSide
  explicitFormula := fun f => by
    simpa [SchwartzRiemannWeilFormulaSideData.residualSide]
      using formulaData.explicitFormula f

/-- Export profiled explicit-formula data as packaged formula-side identity data. -/
noncomputable def toFormulaIdentityData
    {zeroData : SchwartzRiemannWeilProfiledTailZeroData}
    (formulaData :
      SchwartzRiemannWeilProfiledTailExplicitFormulaData zeroData) :
    SchwartzRiemannWeilFormulaIdentityData zeroData.zeroSide where
  sideData :=
    { primeSide := formulaData.primeSide
      poleSide := formulaData.poleSide
      gammaSide := formulaData.gammaSide }
  explicitFormula := fun f => by
    simpa [SchwartzRiemannWeilFormulaSideData.residualSide]
      using formulaData.explicitFormula f

/-- Lift generic tail explicit-formula data to the profiled work-package route. -/
noncomputable def ofTailExplicitFormulaData
    {zeroData : SchwartzRiemannWeilTailZeroData}
    (formulaData : SchwartzRiemannWeilTailExplicitFormulaData zeroData) :
    SchwartzRiemannWeilProfiledTailExplicitFormulaData
      (SchwartzRiemannWeilProfiledTailZeroData.ofTailZeroData zeroData) where
  primeSide := formulaData.primeSide
  poleSide := formulaData.poleSide
  gammaSide := formulaData.gammaSide
  explicitFormula := fun f => by
    rw [SchwartzRiemannWeilProfiledTailZeroData.ofTailZeroData_zeroSide_eq
      zeroData f]
    exact formulaData.explicitFormula f

/-- Forget profiled explicit-formula data to the tail work-package version. -/
noncomputable def toTailExplicitFormulaData
    {zeroData : SchwartzRiemannWeilProfiledTailZeroData}
    (formulaData :
      SchwartzRiemannWeilProfiledTailExplicitFormulaData zeroData) :
    SchwartzRiemannWeilTailExplicitFormulaData zeroData.toTailZeroData where
  primeSide := formulaData.primeSide
  poleSide := formulaData.poleSide
  gammaSide := formulaData.gammaSide
  explicitFormula := formulaData.explicitFormula

/-- Convert profiled explicit-formula data to the decomposed endpoint. -/
noncomputable def toRiemannWeilExplicitFormulaData
    {zeroData : SchwartzRiemannWeilProfiledTailZeroData}
    (formulaData :
      SchwartzRiemannWeilProfiledTailExplicitFormulaData zeroData) :
    SchwartzRiemannWeilExplicitFormulaData :=
  formulaData.toTailExplicitFormulaData.toRiemannWeilExplicitFormulaData

/-- Compact-exhaustion zero-window sums converge to the profiled formula's zero side. -/
theorem tendsto_windowZeroSide
    {zeroData : SchwartzRiemannWeilProfiledTailZeroData}
    (formulaData :
      SchwartzRiemannWeilProfiledTailExplicitFormulaData zeroData)
    (windowExhaustion : ComplexCompactExhaustion)
    (f : SchwartzLineTestFunction) :
    Tendsto
      (fun n : Nat => zeroData.zeroSide.windowZeroSide windowExhaustion n f)
      atTop (nhds (zeroData.zeroSide.zeroSide f)) :=
  formulaData.toTailExplicitFormulaData.tendsto_windowZeroSide
    windowExhaustion f

/--
Compact-exhaustion zero-window sums converge to the residual side of the
profiled explicit formula.
-/
theorem tendsto_windowZeroSide_residualSide
    {zeroData : SchwartzRiemannWeilProfiledTailZeroData}
    (formulaData :
      SchwartzRiemannWeilProfiledTailExplicitFormulaData zeroData)
    (windowExhaustion : ComplexCompactExhaustion)
    (f : SchwartzLineTestFunction) :
    Tendsto
      (fun n : Nat => zeroData.zeroSide.windowZeroSide windowExhaustion n f)
      atTop
        (nhds
          ((formulaData.toRiemannWeilExplicitFormulaData
              |>.toGlobalExplicitFormulaNormalization
              |>.toSchwartzExplicitFormulaNormalization).residualSide f)) :=
  formulaData.toTailExplicitFormulaData
    |>.tendsto_windowZeroSide_residualSide windowExhaustion f

end SchwartzRiemannWeilProfiledTailExplicitFormulaData

/-- Positivity data relative to a profiled tail-generated explicit formula. -/
structure SchwartzRiemannWeilProfiledTailPositivityData
    {zeroData : SchwartzRiemannWeilProfiledTailZeroData}
    (formulaData :
      SchwartzRiemannWeilProfiledTailExplicitFormulaData zeroData) where
  quadraticForm : SchwartzLineTestFunction -> Real
  quadraticForm_eq_zeroSide :
    forall f : SchwartzLineTestFunction,
      quadraticForm f = zeroData.zeroSide.zeroSide f
  positivity :
    forall f : SchwartzLineTestFunction, 0 <= quadraticForm f
  positivity_implies_RHOn_univ :
    (forall f : SchwartzLineTestFunction, 0 <= quadraticForm f) ->
      RHOn (fun _ : Complex => True)

namespace SchwartzRiemannWeilProfiledTailPositivityData

/-- Build profiled positivity data from packaged positivity data. -/
noncomputable def ofPackagedPositivityData
    {zeroData : SchwartzRiemannWeilProfiledTailZeroData}
    {formulaData :
      SchwartzRiemannWeilProfiledTailExplicitFormulaData zeroData}
    (packagedData :
      SchwartzRiemannWeilPackagedPositivityData
        formulaData.toRiemannWeilExplicitFormulaData) :
    SchwartzRiemannWeilProfiledTailPositivityData formulaData where
  quadraticForm := packagedData.identification.quadraticData.quadraticForm
  quadraticForm_eq_zeroSide :=
    packagedData.identification.quadraticForm_eq_zeroSide
  positivity := packagedData.positivity.positivity
  positivity_implies_RHOn_univ :=
    packagedData.criterion.positivity_implies_RHOn_univ

/-- Lift generic tail positivity data to the profiled work-package route. -/
noncomputable def ofTailPositivityData
    {zeroData : SchwartzRiemannWeilTailZeroData}
    {formulaData : SchwartzRiemannWeilTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilTailPositivityData formulaData) :
    SchwartzRiemannWeilProfiledTailPositivityData
      (SchwartzRiemannWeilProfiledTailExplicitFormulaData.ofTailExplicitFormulaData
        formulaData) where
  quadraticForm := positivityData.quadraticForm
  quadraticForm_eq_zeroSide := fun f => by
    rw [SchwartzRiemannWeilProfiledTailZeroData.ofTailZeroData_zeroSide_eq
      zeroData f]
    exact positivityData.quadraticForm_eq_zeroSide f
  positivity := positivityData.positivity
  positivity_implies_RHOn_univ := positivityData.positivity_implies_RHOn_univ

/-- Forget profiled positivity data to the tail work-package version. -/
noncomputable def toTailPositivityData
    {zeroData : SchwartzRiemannWeilProfiledTailZeroData}
    {formulaData :
      SchwartzRiemannWeilProfiledTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilProfiledTailPositivityData formulaData) :
    SchwartzRiemannWeilTailPositivityData
      formulaData.toTailExplicitFormulaData where
  quadraticForm := positivityData.quadraticForm
  quadraticForm_eq_zeroSide := positivityData.quadraticForm_eq_zeroSide
  positivity := positivityData.positivity
  positivity_implies_RHOn_univ :=
    positivityData.positivity_implies_RHOn_univ

/-- Export profiled positivity data as packaged positivity data. -/
noncomputable def toPackagedPositivityData
    {zeroData : SchwartzRiemannWeilProfiledTailZeroData}
    {formulaData :
      SchwartzRiemannWeilProfiledTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilProfiledTailPositivityData formulaData) :
    SchwartzRiemannWeilPackagedPositivityData
      formulaData.toRiemannWeilExplicitFormulaData :=
  SchwartzRiemannWeilPackagedPositivityData.ofPositivityData
    positivityData.toTailPositivityData.toRiemannWeilPositivityData

/-- The profiled work-package quadratic form is the residual side of its explicit formula. -/
theorem quadraticForm_eq_residualSide
    {zeroData : SchwartzRiemannWeilProfiledTailZeroData}
    {formulaData :
      SchwartzRiemannWeilProfiledTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilProfiledTailPositivityData formulaData)
    (f : SchwartzLineTestFunction) :
    positivityData.quadraticForm f =
      (formulaData.toRiemannWeilExplicitFormulaData
        |>.toGlobalExplicitFormulaNormalization
        |>.toSchwartzExplicitFormulaNormalization).residualSide f :=
  positivityData.toTailPositivityData.quadraticForm_eq_residualSide f

/-- The residual side of the profiled explicit formula is its quadratic form. -/
theorem residualSide_eq_quadraticForm
    {zeroData : SchwartzRiemannWeilProfiledTailZeroData}
    {formulaData :
      SchwartzRiemannWeilProfiledTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilProfiledTailPositivityData formulaData)
    (f : SchwartzLineTestFunction) :
    (formulaData.toRiemannWeilExplicitFormulaData
        |>.toGlobalExplicitFormulaNormalization
        |>.toSchwartzExplicitFormulaNormalization).residualSide f =
      positivityData.quadraticForm f :=
  (positivityData.quadraticForm_eq_residualSide f).symm

/-- Assemble profiled work packages into the concrete tail certificate. -/
noncomputable def toTailCertificateData
    {zeroData : SchwartzRiemannWeilProfiledTailZeroData}
    {formulaData :
      SchwartzRiemannWeilProfiledTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilProfiledTailPositivityData formulaData) :
    SchwartzRiemannWeilTailCertificateData :=
  positivityData.toTailPositivityData.toTailCertificateData

/-- Assemble profiled work packages into the decomposed certificate. -/
noncomputable def toCertificateData
    {zeroData : SchwartzRiemannWeilProfiledTailZeroData}
    {formulaData :
      SchwartzRiemannWeilProfiledTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilProfiledTailPositivityData formulaData) :
    SchwartzRiemannWeilCertificateData :=
  positivityData.toTailCertificateData.toCertificateData

/-- Assemble profiled work packages into the global criterion. -/
noncomputable def toGlobalCriterion
    {zeroData : SchwartzRiemannWeilProfiledTailZeroData}
    {formulaData :
      SchwartzRiemannWeilProfiledTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilProfiledTailPositivityData formulaData) :
    SchwartzRiemannWeilGlobalCriterion :=
  positivityData.toTailCertificateData.toGlobalCriterion

/-- Profiled work packages prove universal local RH. -/
theorem RHOn_univ
    {zeroData : SchwartzRiemannWeilProfiledTailZeroData}
    {formulaData :
      SchwartzRiemannWeilProfiledTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilProfiledTailPositivityData formulaData) :
    RHOn (fun _ : Complex => True) :=
  positivityData.toTailCertificateData.RHOn_univ

/-- Profiled work packages prove the project-local RH statement. -/
theorem RHStatement
    {zeroData : SchwartzRiemannWeilProfiledTailZeroData}
    {formulaData :
      SchwartzRiemannWeilProfiledTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilProfiledTailPositivityData formulaData) :
    RiemannHypothesisProject.RHStatement :=
  positivityData.toTailCertificateData.RHStatement

/-- Profiled work packages prove Mathlib's `RiemannHypothesis`. -/
theorem mathlib_RH
    {zeroData : SchwartzRiemannWeilProfiledTailZeroData}
    {formulaData :
      SchwartzRiemannWeilProfiledTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilProfiledTailPositivityData formulaData) :
    RiemannHypothesis :=
  positivityData.toTailCertificateData.mathlib_RH

/-- Window zero sides converge to the profiled work package's quadratic form. -/
theorem tendsto_windowZeroSide_quadraticForm
    {zeroData : SchwartzRiemannWeilProfiledTailZeroData}
    {formulaData :
      SchwartzRiemannWeilProfiledTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilProfiledTailPositivityData formulaData)
    (windowExhaustion : ComplexCompactExhaustion)
    (f : SchwartzLineTestFunction) :
    Tendsto
      (fun n : Nat => zeroData.zeroSide.windowZeroSide windowExhaustion n f)
      atTop (nhds (positivityData.quadraticForm f)) :=
  positivityData.toTailCertificateData.tendsto_windowZeroSide_quadraticForm
    windowExhaustion f

end SchwartzRiemannWeilProfiledTailPositivityData

end RiemannHypothesisProject
