import RiemannHypothesisProject.SchwartzRiemannWeilFormulaSides
import RiemannHypothesisProject.SchwartzRiemannWeilPositivityPackages
import RiemannHypothesisProject.SchwartzRiemannWeilTailCertificateData

/-!
# Tail-generated Riemann-Weil work packages

`SchwartzRiemannWeilTailCertificateData` is the concrete endpoint for the
tail-estimate route, but it is still a large record. This module splits that
endpoint into smaller packages:

* zero data, produced from a separated tail estimate;
* explicit-formula data, relative to that zero side; and
* positivity data, relative to the explicit-formula package.

The final positivity package assembles the full tail certificate and therefore
inherits the project and Mathlib RH consequences.
-/

namespace RiemannHypothesisProject

open Filter
open scoped Topology

/-- Zero-side data produced by a separated polynomial tail estimate. -/
structure SchwartzRiemannWeilTailZeroData where
  exhaustion : ComplexCompactExhaustion
  system : SchwartzRiemannWeilExtensionSystem
  tailEstimate :
    SchwartzRiemannWeilSeparatedPolynomialDecayEstimate exhaustion system

namespace SchwartzRiemannWeilTailZeroData

/-- The zero side generated by the tail estimate. -/
noncomputable def zeroSide
    (zeroData : SchwartzRiemannWeilTailZeroData) :
    SchwartzRiemannWeilZeroSide :=
  zeroData.tailEstimate.toZeroSide

/-- The tail-generated zero side uses the candidate extension-system weight. -/
theorem zeroSide_weight
    (zeroData : SchwartzRiemannWeilTailZeroData)
    (f : SchwartzLineTestFunction)
    (rho : ZetaZeroSubtype) :
    zeroData.zeroSide.weight f rho = zeroData.system.weight f rho :=
  zeroData.tailEstimate.toZeroSide_weight f rho

/-- Compact-exhaustion sums converge for the tail-generated zero side. -/
theorem tendsto_windowZeroSide
    (zeroData : SchwartzRiemannWeilTailZeroData)
    (windowExhaustion : ComplexCompactExhaustion)
    (f : SchwartzLineTestFunction) :
    Tendsto
      (fun n : Nat => zeroData.zeroSide.windowZeroSide windowExhaustion n f)
      atTop (nhds (zeroData.zeroSide.zeroSide f)) :=
  zeroData.tailEstimate.tendsto_windowZeroSide windowExhaustion f

end SchwartzRiemannWeilTailZeroData

/-- Explicit-formula data relative to a tail-generated zero side. -/
structure SchwartzRiemannWeilTailExplicitFormulaData
    (zeroData : SchwartzRiemannWeilTailZeroData) where
  primeSide : SchwartzLineTestFunction -> Real
  poleSide : SchwartzLineTestFunction -> Real
  gammaSide : SchwartzLineTestFunction -> Real
  explicitFormula :
    forall f : SchwartzLineTestFunction,
      zeroData.zeroSide.zeroSide f = primeSide f + poleSide f + gammaSide f

namespace SchwartzRiemannWeilTailExplicitFormulaData

/-- Build tail-relative explicit-formula data from packaged formula-side identity data. -/
noncomputable def ofFormulaIdentityData
    {zeroData : SchwartzRiemannWeilTailZeroData}
    (formulaData :
      SchwartzRiemannWeilFormulaIdentityData zeroData.zeroSide) :
    SchwartzRiemannWeilTailExplicitFormulaData zeroData where
  primeSide := formulaData.sideData.primeSide
  poleSide := formulaData.sideData.poleSide
  gammaSide := formulaData.sideData.gammaSide
  explicitFormula := fun f => by
    simpa [SchwartzRiemannWeilFormulaSideData.residualSide]
      using formulaData.explicitFormula f

/-- Export tail-relative explicit-formula data as packaged formula-side identity data. -/
noncomputable def toFormulaIdentityData
    {zeroData : SchwartzRiemannWeilTailZeroData}
    (formulaData :
      SchwartzRiemannWeilTailExplicitFormulaData zeroData) :
    SchwartzRiemannWeilFormulaIdentityData zeroData.zeroSide where
  sideData :=
    { primeSide := formulaData.primeSide
      poleSide := formulaData.poleSide
      gammaSide := formulaData.gammaSide }
  explicitFormula := fun f => by
    simpa [SchwartzRiemannWeilFormulaSideData.residualSide]
      using formulaData.explicitFormula f

/-- Convert tail-relative explicit-formula data to the decomposed endpoint. -/
noncomputable def toRiemannWeilExplicitFormulaData
    {zeroData : SchwartzRiemannWeilTailZeroData}
    (formulaData :
      SchwartzRiemannWeilTailExplicitFormulaData zeroData) :
    SchwartzRiemannWeilExplicitFormulaData where
  zeroSide := zeroData.zeroSide
  primeSide := formulaData.primeSide
  poleSide := formulaData.poleSide
  gammaSide := formulaData.gammaSide
  explicitFormula := formulaData.explicitFormula

/-- Compact-exhaustion zero-window sums converge to the tail formula's zero side. -/
theorem tendsto_windowZeroSide
    {zeroData : SchwartzRiemannWeilTailZeroData}
    (formulaData :
      SchwartzRiemannWeilTailExplicitFormulaData zeroData)
    (windowExhaustion : ComplexCompactExhaustion)
    (f : SchwartzLineTestFunction) :
    Tendsto
      (fun n : Nat => zeroData.zeroSide.windowZeroSide windowExhaustion n f)
      atTop (nhds (zeroData.zeroSide.zeroSide f)) :=
  formulaData.toRiemannWeilExplicitFormulaData.tendsto_windowZeroSide
    windowExhaustion f

/--
Compact-exhaustion zero-window sums converge to the residual side of the
tail-relative explicit formula.
-/
theorem tendsto_windowZeroSide_residualSide
    {zeroData : SchwartzRiemannWeilTailZeroData}
    (formulaData :
      SchwartzRiemannWeilTailExplicitFormulaData zeroData)
    (windowExhaustion : ComplexCompactExhaustion)
    (f : SchwartzLineTestFunction) :
    Tendsto
      (fun n : Nat => zeroData.zeroSide.windowZeroSide windowExhaustion n f)
      atTop
        (nhds
          ((formulaData.toRiemannWeilExplicitFormulaData
              |>.toGlobalExplicitFormulaNormalization
              |>.toSchwartzExplicitFormulaNormalization).residualSide f)) :=
  formulaData.toRiemannWeilExplicitFormulaData
    |>.tendsto_windowZeroSide_residualSide windowExhaustion f

end SchwartzRiemannWeilTailExplicitFormulaData

/-- Positivity data relative to a tail-generated explicit formula. -/
structure SchwartzRiemannWeilTailPositivityData
    {zeroData : SchwartzRiemannWeilTailZeroData}
    (formulaData : SchwartzRiemannWeilTailExplicitFormulaData zeroData) where
  quadraticForm : SchwartzLineTestFunction -> Real
  quadraticForm_eq_zeroSide :
    forall f : SchwartzLineTestFunction,
      quadraticForm f = zeroData.zeroSide.zeroSide f
  positivity :
    forall f : SchwartzLineTestFunction, 0 <= quadraticForm f
  positivity_implies_RHOn_univ :
    (forall f : SchwartzLineTestFunction, 0 <= quadraticForm f) ->
      RHOn (fun _ : Complex => True)

namespace SchwartzRiemannWeilTailPositivityData

/-- Build tail-relative positivity data from packaged positivity data. -/
noncomputable def ofPackagedPositivityData
    {zeroData : SchwartzRiemannWeilTailZeroData}
    {formulaData : SchwartzRiemannWeilTailExplicitFormulaData zeroData}
    (packagedData :
      SchwartzRiemannWeilPackagedPositivityData
        formulaData.toRiemannWeilExplicitFormulaData) :
    SchwartzRiemannWeilTailPositivityData formulaData where
  quadraticForm := packagedData.identification.quadraticData.quadraticForm
  quadraticForm_eq_zeroSide :=
    packagedData.identification.quadraticForm_eq_zeroSide
  positivity := packagedData.positivity.positivity
  positivity_implies_RHOn_univ :=
    packagedData.criterion.positivity_implies_RHOn_univ

/-- Convert tail-relative positivity data to the decomposed endpoint. -/
noncomputable def toRiemannWeilPositivityData
    {zeroData : SchwartzRiemannWeilTailZeroData}
    {formulaData : SchwartzRiemannWeilTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilTailPositivityData formulaData) :
    SchwartzRiemannWeilPositivityData
      formulaData.toRiemannWeilExplicitFormulaData where
  quadraticForm := positivityData.quadraticForm
  quadraticForm_eq_zeroSide := positivityData.quadraticForm_eq_zeroSide
  positivity := positivityData.positivity
  positivity_implies_RHOn_univ :=
    positivityData.positivity_implies_RHOn_univ

/-- Export tail-relative positivity data as packaged positivity data. -/
noncomputable def toPackagedPositivityData
    {zeroData : SchwartzRiemannWeilTailZeroData}
    {formulaData : SchwartzRiemannWeilTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilTailPositivityData formulaData) :
    SchwartzRiemannWeilPackagedPositivityData
      formulaData.toRiemannWeilExplicitFormulaData :=
  SchwartzRiemannWeilPackagedPositivityData.ofPositivityData
    positivityData.toRiemannWeilPositivityData

/-- The tail work-package quadratic form is the residual side of its explicit formula. -/
theorem quadraticForm_eq_residualSide
    {zeroData : SchwartzRiemannWeilTailZeroData}
    {formulaData : SchwartzRiemannWeilTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilTailPositivityData formulaData)
    (f : SchwartzLineTestFunction) :
    positivityData.quadraticForm f =
      (formulaData.toRiemannWeilExplicitFormulaData
        |>.toGlobalExplicitFormulaNormalization
        |>.toSchwartzExplicitFormulaNormalization).residualSide f :=
  positivityData.toRiemannWeilPositivityData.quadraticForm_eq_residualSide f

/-- The residual side of the tail work-package explicit formula is its quadratic form. -/
theorem residualSide_eq_quadraticForm
    {zeroData : SchwartzRiemannWeilTailZeroData}
    {formulaData : SchwartzRiemannWeilTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilTailPositivityData formulaData)
    (f : SchwartzLineTestFunction) :
    (formulaData.toRiemannWeilExplicitFormulaData
        |>.toGlobalExplicitFormulaNormalization
        |>.toSchwartzExplicitFormulaNormalization).residualSide f =
      positivityData.quadraticForm f :=
  (positivityData.quadraticForm_eq_residualSide f).symm

/-- Assemble the tail work packages into the concrete tail certificate. -/
noncomputable def toTailCertificateData
    {zeroData : SchwartzRiemannWeilTailZeroData}
    {formulaData : SchwartzRiemannWeilTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilTailPositivityData formulaData) :
    SchwartzRiemannWeilTailCertificateData where
  exhaustion := zeroData.exhaustion
  system := zeroData.system
  tailEstimate := zeroData.tailEstimate
  primeSide := formulaData.primeSide
  poleSide := formulaData.poleSide
  gammaSide := formulaData.gammaSide
  explicitFormula := formulaData.explicitFormula
  quadraticForm := positivityData.quadraticForm
  quadraticForm_eq_zeroSide := positivityData.quadraticForm_eq_zeroSide
  positivity := positivityData.positivity
  positivity_implies_RHOn_univ :=
    positivityData.positivity_implies_RHOn_univ

/-- Assemble the tail work packages into the decomposed certificate. -/
noncomputable def toCertificateData
    {zeroData : SchwartzRiemannWeilTailZeroData}
    {formulaData : SchwartzRiemannWeilTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilTailPositivityData formulaData) :
    SchwartzRiemannWeilCertificateData :=
  positivityData.toTailCertificateData.toCertificateData

/-- Assemble the tail work packages into the global criterion. -/
noncomputable def toGlobalCriterion
    {zeroData : SchwartzRiemannWeilTailZeroData}
    {formulaData : SchwartzRiemannWeilTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilTailPositivityData formulaData) :
    SchwartzRiemannWeilGlobalCriterion :=
  positivityData.toTailCertificateData.toGlobalCriterion

/-- Tail work packages prove universal local RH. -/
theorem RHOn_univ
    {zeroData : SchwartzRiemannWeilTailZeroData}
    {formulaData : SchwartzRiemannWeilTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilTailPositivityData formulaData) :
    RHOn (fun _ : Complex => True) :=
  positivityData.toTailCertificateData.RHOn_univ

/-- Tail work packages prove the project-local RH statement. -/
theorem RHStatement
    {zeroData : SchwartzRiemannWeilTailZeroData}
    {formulaData : SchwartzRiemannWeilTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilTailPositivityData formulaData) :
    RiemannHypothesisProject.RHStatement :=
  positivityData.toTailCertificateData.RHStatement

/-- Tail work packages prove Mathlib's `RiemannHypothesis`. -/
theorem mathlib_RH
    {zeroData : SchwartzRiemannWeilTailZeroData}
    {formulaData : SchwartzRiemannWeilTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilTailPositivityData formulaData) :
    RiemannHypothesis :=
  positivityData.toTailCertificateData.mathlib_RH

/-- Window zero sides converge to the tail work package's quadratic form. -/
theorem tendsto_windowZeroSide_quadraticForm
    {zeroData : SchwartzRiemannWeilTailZeroData}
    {formulaData : SchwartzRiemannWeilTailExplicitFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilTailPositivityData formulaData)
    (windowExhaustion : ComplexCompactExhaustion)
    (f : SchwartzLineTestFunction) :
    Tendsto
      (fun n : Nat => zeroData.zeroSide.windowZeroSide windowExhaustion n f)
      atTop (nhds (positivityData.quadraticForm f)) :=
  positivityData.toTailCertificateData.tendsto_windowZeroSide_quadraticForm
    windowExhaustion f

end SchwartzRiemannWeilTailPositivityData

end RiemannHypothesisProject
