import RiemannHypothesisProject.SchwartzRiemannWeilAnalyticInputs

/-!
# P-series envelope targets for the Riemann-Weil route

`SchwartzRiemannWeilProfiledShellFormulaResidualInputData` is the preferred
final input package. This file names more analytic-facing special cases:
eventual p-series bounds for the extension envelope at zeta-zero arguments,
their cutoff-zero specialization, matching zero counting, formula identity, and
formula-side residual positivity. Lean assembles these into the final endpoint.

This keeps the next mathematical work unit explicit without adding axioms or
assuming any analytic theorem.
-/

namespace RiemannHypothesisProject

open Filter
open scoped Topology

/--
Zero-side data for the cutoff-zero p-series envelope route.

This package isolates the analytic estimates that produce the zero side:
* a complex extension envelope;
* a direct p-series envelope bound at every zeta-zero argument;
* first-entry zero counting with cutoff zero;
* the p-series decay margin beating zero-count growth by more than one.
-/
structure SchwartzRiemannWeilPSeriesEnvelopeZeroData where
  exhaustion : ComplexCompactExhaustion
  system : SchwartzRiemannWeilExtensionSystem
  growthBound : SchwartzRiemannWeilExtensionGrowthBound system
  zeroConstant : SchwartzLineTestFunction -> Real
  decayExponent : SchwartzLineTestFunction -> Real
  zeroConstant_nonneg :
    forall f : SchwartzLineTestFunction, 0 <= zeroConstant f
  pseriesBound_nonneg :
    forall (f : SchwartzLineTestFunction) (n : Nat),
      0 <= zeroConstant f *
        (1 / |(n : Real) + 1| ^ decayExponent f)
  envelope_zeroArgument_le_pseries :
    forall (f : SchwartzLineTestFunction) (rho : ZetaZeroSubtype),
      growthBound.envelope f (riemannWeilZeroArgument (rho : Complex)) <=
        zeroConstant f *
          (1 /
            |(exhaustion.zetaZeroFirstEntryIndex rho : Real) + 1| ^
              decayExponent f)
  counting : SchwartzRiemannWeilPolynomialZeroCountingEstimate exhaustion
  counting_cutoff_eq_zero : counting.cutoff = 0
  growth_add_one_lt_decay :
    forall f : SchwartzLineTestFunction,
      counting.growth + 1 < decayExponent f

namespace SchwartzRiemannWeilPSeriesEnvelopeZeroData

/-- The shell-decay data assembled from p-series envelope zero data. -/
noncomputable def shellDecay
    (zeroData : SchwartzRiemannWeilPSeriesEnvelopeZeroData) :
    SchwartzRiemannWeilExtensionShellDecayEstimate
      zeroData.exhaustion zeroData.system :=
  SchwartzRiemannWeilProfiledShellFormulaResidualInputData.shellDecayOfGlobalPSeriesEnvelopeBound
    zeroData.growthBound zeroData.zeroConstant zeroData.decayExponent
    zeroData.zeroConstant_nonneg zeroData.pseriesBound_nonneg
    zeroData.envelope_zeroArgument_le_pseries

/-- The profiled separated tail estimate assembled from p-series zero data. -/
noncomputable def profiledTailEstimate
    (zeroData : SchwartzRiemannWeilPSeriesEnvelopeZeroData) :
    SchwartzRiemannWeilProfiledSeparatedTailEstimate
      zeroData.exhaustion zeroData.system :=
  SchwartzRiemannWeilProfiledShellFormulaResidualInputData.profiledTailEstimateOfGlobalPSeriesEnvelopeAndCounting
    zeroData.growthBound zeroData.zeroConstant zeroData.decayExponent
    zeroData.zeroConstant_nonneg zeroData.pseriesBound_nonneg
    zeroData.envelope_zeroArgument_le_pseries zeroData.counting
    zeroData.counting_cutoff_eq_zero zeroData.growth_add_one_lt_decay

/-- The zero side generated by the p-series envelope estimate. -/
noncomputable def zeroSide
    (zeroData : SchwartzRiemannWeilPSeriesEnvelopeZeroData) :
    SchwartzRiemannWeilZeroSide :=
  zeroData.profiledTailEstimate.toZeroSide

/-- The generated zero side uses the candidate extension-system weight. -/
theorem zeroSide_weight
    (zeroData : SchwartzRiemannWeilPSeriesEnvelopeZeroData)
    (f : SchwartzLineTestFunction)
    (rho : ZetaZeroSubtype) :
    zeroData.zeroSide.weight f rho = zeroData.system.weight f rho :=
  zeroData.profiledTailEstimate.toZeroSide_weight f rho

/-- Compact-exhaustion sums converge for the generated zero side. -/
theorem tendsto_windowZeroSide
    (zeroData : SchwartzRiemannWeilPSeriesEnvelopeZeroData)
    (windowExhaustion : ComplexCompactExhaustion)
    (f : SchwartzLineTestFunction) :
    Tendsto
      (fun n : Nat => zeroData.zeroSide.windowZeroSide windowExhaustion n f)
      atTop (nhds (zeroData.zeroSide.zeroSide f)) :=
  zeroData.profiledTailEstimate.tendsto_windowZeroSide windowExhaustion f

end SchwartzRiemannWeilPSeriesEnvelopeZeroData

/-- Formula identity data relative to p-series envelope zero data. -/
structure SchwartzRiemannWeilPSeriesEnvelopeFormulaData
    (zeroData : SchwartzRiemannWeilPSeriesEnvelopeZeroData) where
  formulaData :
    SchwartzRiemannWeilFormulaIdentityData zeroData.zeroSide

namespace SchwartzRiemannWeilPSeriesEnvelopeFormulaData

/-- Build cutoff-zero formula data directly from raw formula sides. -/
noncomputable def ofRawSides
    {zeroData : SchwartzRiemannWeilPSeriesEnvelopeZeroData}
    (primeSide poleSide gammaSide : SchwartzLineTestFunction -> Real)
    (explicitFormula :
      forall f : SchwartzLineTestFunction,
        zeroData.zeroSide.zeroSide f =
          primeSide f + poleSide f + gammaSide f) :
    SchwartzRiemannWeilPSeriesEnvelopeFormulaData zeroData where
  formulaData :=
    SchwartzRiemannWeilFormulaIdentityData.ofRawSides
      primeSide poleSide gammaSide explicitFormula

/-- Compact-exhaustion sums converge to the formula-side residual expression. -/
theorem tendsto_windowZeroSide_formulaResidualSide
    {zeroData : SchwartzRiemannWeilPSeriesEnvelopeZeroData}
    (formulaData :
      SchwartzRiemannWeilPSeriesEnvelopeFormulaData zeroData)
    (windowExhaustion : ComplexCompactExhaustion)
    (f : SchwartzLineTestFunction) :
    Tendsto
      (fun n : Nat => zeroData.zeroSide.windowZeroSide windowExhaustion n f)
      atTop (nhds (formulaData.formulaData.sideData.residualSide f)) := by
  rw [← formulaData.formulaData.explicitFormula f]
  exact zeroData.tendsto_windowZeroSide windowExhaustion f

end SchwartzRiemannWeilPSeriesEnvelopeFormulaData

/-- Formula-side residual positivity relative to p-series envelope formula data. -/
structure SchwartzRiemannWeilPSeriesEnvelopeResidualPositivityData
    {zeroData : SchwartzRiemannWeilPSeriesEnvelopeZeroData}
    (formulaData : SchwartzRiemannWeilPSeriesEnvelopeFormulaData zeroData) where
  formulaResidualData :
    SchwartzRiemannWeilFormulaResidualPositivityData formulaData.formulaData

namespace SchwartzRiemannWeilPSeriesEnvelopeResidualPositivityData

/-- Build cutoff-zero residual positivity directly from raw residual-side data. -/
noncomputable def ofRawResidualPositivity
    {zeroData : SchwartzRiemannWeilPSeriesEnvelopeZeroData}
    {formulaData : SchwartzRiemannWeilPSeriesEnvelopeFormulaData zeroData}
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= formulaData.formulaData.sideData.residualSide f)
    (residual_positivity_implies_RHOn_univ :
      (forall f : SchwartzLineTestFunction,
        0 <= formulaData.formulaData.sideData.residualSide f) ->
        RHOn (fun _ : Complex => True)) :
    SchwartzRiemannWeilPSeriesEnvelopeResidualPositivityData formulaData where
  formulaResidualData :=
    SchwartzRiemannWeilFormulaResidualPositivityData.ofRawResidualPositivity
      residual_nonneg residual_positivity_implies_RHOn_univ

/-- The packaged formula residual side is nonnegative. -/
theorem formulaResidual_nonneg
    {zeroData : SchwartzRiemannWeilPSeriesEnvelopeZeroData}
    {formulaData : SchwartzRiemannWeilPSeriesEnvelopeFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilPSeriesEnvelopeResidualPositivityData formulaData)
    (f : SchwartzLineTestFunction) :
    0 <= formulaData.formulaData.sideData.residualSide f :=
  positivityData.formulaResidualData.residual_nonneg f

/-- Formula-side residual positivity proves universal local RH. -/
theorem formulaResidual_positivity_implies_RHOn_univ
    {zeroData : SchwartzRiemannWeilPSeriesEnvelopeZeroData}
    {formulaData : SchwartzRiemannWeilPSeriesEnvelopeFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilPSeriesEnvelopeResidualPositivityData formulaData) :
    (forall f : SchwartzLineTestFunction,
      0 <= formulaData.formulaData.sideData.residualSide f) ->
      RHOn (fun _ : Complex => True) :=
  positivityData.formulaResidualData.residual_positivity_implies_RHOn_univ

end SchwartzRiemannWeilPSeriesEnvelopeResidualPositivityData

/--
Zero-side data for the eventual p-series envelope route.

This is the realistic version of the p-series envelope target: finite-prefix
behavior is controlled by `prefixBound`, while the p-series tail begins after
`cutoff`.
-/
structure SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData where
  exhaustion : ComplexCompactExhaustion
  system : SchwartzRiemannWeilExtensionSystem
  growthBound : SchwartzRiemannWeilExtensionGrowthBound system
  cutoff : Nat
  prefixBound : SchwartzLineTestFunction -> Nat -> Real
  zeroConstant : SchwartzLineTestFunction -> Real
  decayExponent : SchwartzLineTestFunction -> Real
  zeroConstant_nonneg :
    forall f : SchwartzLineTestFunction, 0 <= zeroConstant f
  prefixBound_nonneg :
    forall (f : SchwartzLineTestFunction) (n : Nat), 0 <= prefixBound f n
  pseriesBound_nonneg :
    forall (f : SchwartzLineTestFunction) (n : Nat),
      0 <= zeroConstant f *
        (1 / |(n : Real) + 1| ^ decayExponent f)
  envelope_zeroArgument_le_eventualPSeries :
    forall (f : SchwartzLineTestFunction) (rho : ZetaZeroSubtype),
      growthBound.envelope f (riemannWeilZeroArgument (rho : Complex)) <=
        SchwartzRiemannWeilExtensionShellDecayEstimate.eventualPSeriesShellBound
          cutoff prefixBound zeroConstant decayExponent f
          (exhaustion.zetaZeroFirstEntryIndex rho)
  counting : SchwartzRiemannWeilPolynomialZeroCountingEstimate exhaustion
  counting_cutoff_eq : counting.cutoff = cutoff
  growth_add_one_lt_decay :
    forall f : SchwartzLineTestFunction,
      counting.growth + 1 < decayExponent f

namespace SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData

/-- Cutoff-zero p-series zero data is a special case of eventual p-series zero data. -/
noncomputable def ofCutoffZero
    (zeroData : SchwartzRiemannWeilPSeriesEnvelopeZeroData) :
    SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData where
  exhaustion := zeroData.exhaustion
  system := zeroData.system
  growthBound := zeroData.growthBound
  cutoff := 0
  prefixBound := fun f n =>
    zeroData.zeroConstant f *
      (1 / |(n : Real) + 1| ^ zeroData.decayExponent f)
  zeroConstant := zeroData.zeroConstant
  decayExponent := zeroData.decayExponent
  zeroConstant_nonneg := zeroData.zeroConstant_nonneg
  prefixBound_nonneg := zeroData.pseriesBound_nonneg
  pseriesBound_nonneg := zeroData.pseriesBound_nonneg
  envelope_zeroArgument_le_eventualPSeries := fun f rho => by
    simpa [SchwartzRiemannWeilExtensionShellDecayEstimate.eventualPSeriesShellBound]
      using zeroData.envelope_zeroArgument_le_pseries f rho
  counting := zeroData.counting
  counting_cutoff_eq := zeroData.counting_cutoff_eq_zero
  growth_add_one_lt_decay := zeroData.growth_add_one_lt_decay

/--
Build eventual p-series envelope zero data from an exact polynomial
shell-cardinality bound and an eventual p-series envelope bound.
-/
noncomputable def ofExactShellCardAndEventualPSeriesEnvelopeBound
    {exhaustion : ComplexCompactExhaustion}
    {system : SchwartzRiemannWeilExtensionSystem}
    (growthBound : SchwartzRiemannWeilExtensionGrowthBound system)
    (cutoff : Nat)
    (prefixBound : SchwartzLineTestFunction -> Nat -> Real)
    (zeroConstant : SchwartzLineTestFunction -> Real)
    (decayExponent : SchwartzLineTestFunction -> Real)
    (shellCardConstant growth : Real)
    (zeroConstant_nonneg :
      forall f : SchwartzLineTestFunction, 0 <= zeroConstant f)
    (prefixBound_nonneg :
      forall (f : SchwartzLineTestFunction) (n : Nat), 0 <= prefixBound f n)
    (pseriesBound_nonneg :
      forall (f : SchwartzLineTestFunction) (n : Nat),
        0 <= zeroConstant f *
          (1 / |(n : Real) + 1| ^ decayExponent f))
    (shellCardConstant_nonneg : 0 <= shellCardConstant)
    (tail_shellCard_le :
      forall n : Nat,
        ((exhaustion.zetaZeroFirstEntryShell (n + cutoff)).card : Real) <=
          shellCardConstant * |(n : Real) + 1| ^ growth)
    (envelope_zeroArgument_le_eventualPSeries :
      forall (f : SchwartzLineTestFunction) (rho : ZetaZeroSubtype),
        growthBound.envelope f (riemannWeilZeroArgument (rho : Complex)) <=
          SchwartzRiemannWeilExtensionShellDecayEstimate.eventualPSeriesShellBound
            cutoff prefixBound zeroConstant decayExponent f
            (exhaustion.zetaZeroFirstEntryIndex rho))
    (growth_add_one_lt_decay :
      forall f : SchwartzLineTestFunction, growth + 1 < decayExponent f) :
    SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData where
  exhaustion := exhaustion
  system := system
  growthBound := growthBound
  cutoff := cutoff
  prefixBound := prefixBound
  zeroConstant := zeroConstant
  decayExponent := decayExponent
  zeroConstant_nonneg := zeroConstant_nonneg
  prefixBound_nonneg := prefixBound_nonneg
  pseriesBound_nonneg := pseriesBound_nonneg
  envelope_zeroArgument_le_eventualPSeries :=
    envelope_zeroArgument_le_eventualPSeries
  counting :=
    SchwartzRiemannWeilPolynomialZeroCountingEstimate.ofExactShellCardPolynomialBound
      exhaustion cutoff shellCardConstant growth shellCardConstant_nonneg
      tail_shellCard_le
  counting_cutoff_eq := rfl
  growth_add_one_lt_decay := growth_add_one_lt_decay

/--
Build eventual p-series envelope zero data from a uniformly bounded tail shell
cardinality estimate and an eventual p-series envelope bound.
-/
noncomputable def ofUniformTailShellCardAndEventualPSeriesEnvelopeBound
    {exhaustion : ComplexCompactExhaustion}
    {system : SchwartzRiemannWeilExtensionSystem}
    (growthBound : SchwartzRiemannWeilExtensionGrowthBound system)
    (cutoff : Nat)
    (prefixBound : SchwartzLineTestFunction -> Nat -> Real)
    (zeroConstant : SchwartzLineTestFunction -> Real)
    (decayExponent : SchwartzLineTestFunction -> Real)
    (shellCardConstant : Real)
    (zeroConstant_nonneg :
      forall f : SchwartzLineTestFunction, 0 <= zeroConstant f)
    (prefixBound_nonneg :
      forall (f : SchwartzLineTestFunction) (n : Nat), 0 <= prefixBound f n)
    (pseriesBound_nonneg :
      forall (f : SchwartzLineTestFunction) (n : Nat),
        0 <= zeroConstant f *
          (1 / |(n : Real) + 1| ^ decayExponent f))
    (shellCardConstant_nonneg : 0 <= shellCardConstant)
    (tail_shellCard_le :
      forall n : Nat,
        ((exhaustion.zetaZeroFirstEntryShell (n + cutoff)).card : Real) <=
          shellCardConstant)
    (envelope_zeroArgument_le_eventualPSeries :
      forall (f : SchwartzLineTestFunction) (rho : ZetaZeroSubtype),
        growthBound.envelope f (riemannWeilZeroArgument (rho : Complex)) <=
          SchwartzRiemannWeilExtensionShellDecayEstimate.eventualPSeriesShellBound
            cutoff prefixBound zeroConstant decayExponent f
            (exhaustion.zetaZeroFirstEntryIndex rho))
    (growth_add_one_lt_decay :
      forall f : SchwartzLineTestFunction, (0 : Real) + 1 < decayExponent f) :
    SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData where
  exhaustion := exhaustion
  system := system
  growthBound := growthBound
  cutoff := cutoff
  prefixBound := prefixBound
  zeroConstant := zeroConstant
  decayExponent := decayExponent
  zeroConstant_nonneg := zeroConstant_nonneg
  prefixBound_nonneg := prefixBound_nonneg
  pseriesBound_nonneg := pseriesBound_nonneg
  envelope_zeroArgument_le_eventualPSeries :=
    envelope_zeroArgument_le_eventualPSeries
  counting :=
    SchwartzRiemannWeilPolynomialZeroCountingEstimate.ofUniformTailShellCardBound
      exhaustion cutoff shellCardConstant shellCardConstant_nonneg
      tail_shellCard_le
  counting_cutoff_eq := rfl
  growth_add_one_lt_decay := growth_add_one_lt_decay

/--
Build eventual p-series envelope zero data from a polynomial bound on
cumulative compact-window zero counts and an eventual p-series envelope bound.
-/
noncomputable def ofWindowCardAndEventualPSeriesEnvelopeBound
    {exhaustion : ComplexCompactExhaustion}
    {system : SchwartzRiemannWeilExtensionSystem}
    (growthBound : SchwartzRiemannWeilExtensionGrowthBound system)
    (cutoff : Nat)
    (prefixBound : SchwartzLineTestFunction -> Nat -> Real)
    (zeroConstant : SchwartzLineTestFunction -> Real)
    (decayExponent : SchwartzLineTestFunction -> Real)
    (shellCardConstant growth : Real)
    (zeroConstant_nonneg :
      forall f : SchwartzLineTestFunction, 0 <= zeroConstant f)
    (prefixBound_nonneg :
      forall (f : SchwartzLineTestFunction) (n : Nat), 0 <= prefixBound f n)
    (pseriesBound_nonneg :
      forall (f : SchwartzLineTestFunction) (n : Nat),
        0 <= zeroConstant f *
          (1 / |(n : Real) + 1| ^ decayExponent f))
    (shellCardConstant_nonneg : 0 <= shellCardConstant)
    (tail_windowCard_le :
      forall n : Nat,
        ((exhaustion.zetaZeroSubtypeFinset (n + cutoff)).card : Real) <=
          shellCardConstant * |(n : Real) + 1| ^ growth)
    (envelope_zeroArgument_le_eventualPSeries :
      forall (f : SchwartzLineTestFunction) (rho : ZetaZeroSubtype),
        growthBound.envelope f (riemannWeilZeroArgument (rho : Complex)) <=
          SchwartzRiemannWeilExtensionShellDecayEstimate.eventualPSeriesShellBound
            cutoff prefixBound zeroConstant decayExponent f
            (exhaustion.zetaZeroFirstEntryIndex rho))
    (growth_add_one_lt_decay :
      forall f : SchwartzLineTestFunction, growth + 1 < decayExponent f) :
    SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData where
  exhaustion := exhaustion
  system := system
  growthBound := growthBound
  cutoff := cutoff
  prefixBound := prefixBound
  zeroConstant := zeroConstant
  decayExponent := decayExponent
  zeroConstant_nonneg := zeroConstant_nonneg
  prefixBound_nonneg := prefixBound_nonneg
  pseriesBound_nonneg := pseriesBound_nonneg
  envelope_zeroArgument_le_eventualPSeries :=
    envelope_zeroArgument_le_eventualPSeries
  counting :=
    SchwartzRiemannWeilPolynomialZeroCountingEstimate.ofWindowCardPolynomialBound
      exhaustion cutoff shellCardConstant growth shellCardConstant_nonneg
      tail_windowCard_le
  counting_cutoff_eq := rfl
  growth_add_one_lt_decay := growth_add_one_lt_decay

/--
Build eventual p-series envelope zero data from a uniformly bounded cumulative
compact-window zero-count estimate and an eventual p-series envelope bound.
-/
noncomputable def ofUniformTailWindowCardAndEventualPSeriesEnvelopeBound
    {exhaustion : ComplexCompactExhaustion}
    {system : SchwartzRiemannWeilExtensionSystem}
    (growthBound : SchwartzRiemannWeilExtensionGrowthBound system)
    (cutoff : Nat)
    (prefixBound : SchwartzLineTestFunction -> Nat -> Real)
    (zeroConstant : SchwartzLineTestFunction -> Real)
    (decayExponent : SchwartzLineTestFunction -> Real)
    (shellCardConstant : Real)
    (zeroConstant_nonneg :
      forall f : SchwartzLineTestFunction, 0 <= zeroConstant f)
    (prefixBound_nonneg :
      forall (f : SchwartzLineTestFunction) (n : Nat), 0 <= prefixBound f n)
    (pseriesBound_nonneg :
      forall (f : SchwartzLineTestFunction) (n : Nat),
        0 <= zeroConstant f *
          (1 / |(n : Real) + 1| ^ decayExponent f))
    (shellCardConstant_nonneg : 0 <= shellCardConstant)
    (tail_windowCard_le :
      forall n : Nat,
        ((exhaustion.zetaZeroSubtypeFinset (n + cutoff)).card : Real) <=
          shellCardConstant)
    (envelope_zeroArgument_le_eventualPSeries :
      forall (f : SchwartzLineTestFunction) (rho : ZetaZeroSubtype),
        growthBound.envelope f (riemannWeilZeroArgument (rho : Complex)) <=
          SchwartzRiemannWeilExtensionShellDecayEstimate.eventualPSeriesShellBound
            cutoff prefixBound zeroConstant decayExponent f
            (exhaustion.zetaZeroFirstEntryIndex rho))
    (growth_add_one_lt_decay :
      forall f : SchwartzLineTestFunction, (0 : Real) + 1 < decayExponent f) :
    SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData where
  exhaustion := exhaustion
  system := system
  growthBound := growthBound
  cutoff := cutoff
  prefixBound := prefixBound
  zeroConstant := zeroConstant
  decayExponent := decayExponent
  zeroConstant_nonneg := zeroConstant_nonneg
  prefixBound_nonneg := prefixBound_nonneg
  pseriesBound_nonneg := pseriesBound_nonneg
  envelope_zeroArgument_le_eventualPSeries :=
    envelope_zeroArgument_le_eventualPSeries
  counting :=
    SchwartzRiemannWeilPolynomialZeroCountingEstimate.ofUniformTailWindowCardBound
      exhaustion cutoff shellCardConstant shellCardConstant_nonneg
      tail_windowCard_le
  counting_cutoff_eq := rfl
  growth_add_one_lt_decay := growth_add_one_lt_decay

/--
Build eventual p-series envelope zero data from a named cumulative
compact-window zero-counting estimate and an eventual p-series envelope bound.
-/
noncomputable def ofCumulativeWindowCountingAndEventualPSeriesEnvelopeBound
    {exhaustion : ComplexCompactExhaustion}
    {system : SchwartzRiemannWeilExtensionSystem}
    (growthBound : SchwartzRiemannWeilExtensionGrowthBound system)
    (counting :
      SchwartzRiemannWeilCumulativeWindowCountingEstimate exhaustion)
    (prefixBound : SchwartzLineTestFunction -> Nat -> Real)
    (zeroConstant : SchwartzLineTestFunction -> Real)
    (decayExponent : SchwartzLineTestFunction -> Real)
    (zeroConstant_nonneg :
      forall f : SchwartzLineTestFunction, 0 <= zeroConstant f)
    (prefixBound_nonneg :
      forall (f : SchwartzLineTestFunction) (n : Nat), 0 <= prefixBound f n)
    (pseriesBound_nonneg :
      forall (f : SchwartzLineTestFunction) (n : Nat),
        0 <= zeroConstant f *
          (1 / |(n : Real) + 1| ^ decayExponent f))
    (envelope_zeroArgument_le_eventualPSeries :
      forall (f : SchwartzLineTestFunction) (rho : ZetaZeroSubtype),
        growthBound.envelope f (riemannWeilZeroArgument (rho : Complex)) <=
          SchwartzRiemannWeilExtensionShellDecayEstimate.eventualPSeriesShellBound
            counting.cutoff prefixBound zeroConstant decayExponent f
            (exhaustion.zetaZeroFirstEntryIndex rho))
    (growth_add_one_lt_decay :
      forall f : SchwartzLineTestFunction,
        counting.growth + 1 < decayExponent f) :
    SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData where
  exhaustion := exhaustion
  system := system
  growthBound := growthBound
  cutoff := counting.cutoff
  prefixBound := prefixBound
  zeroConstant := zeroConstant
  decayExponent := decayExponent
  zeroConstant_nonneg := zeroConstant_nonneg
  prefixBound_nonneg := prefixBound_nonneg
  pseriesBound_nonneg := pseriesBound_nonneg
  envelope_zeroArgument_le_eventualPSeries :=
    envelope_zeroArgument_le_eventualPSeries
  counting := counting.toPolynomialZeroCountingEstimate
  counting_cutoff_eq := rfl
  growth_add_one_lt_decay := growth_add_one_lt_decay

/-- The shell-decay data assembled from eventual p-series envelope zero data. -/
noncomputable def shellDecay
    (zeroData : SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData) :
    SchwartzRiemannWeilExtensionShellDecayEstimate
      zeroData.exhaustion zeroData.system :=
  SchwartzRiemannWeilExtensionShellDecayEstimate.ofEventualPSeriesEnvelopeBound
    zeroData.growthBound zeroData.cutoff zeroData.prefixBound
    zeroData.zeroConstant zeroData.decayExponent
    zeroData.zeroConstant_nonneg zeroData.prefixBound_nonneg
    zeroData.pseriesBound_nonneg
    zeroData.envelope_zeroArgument_le_eventualPSeries

/-- The profiled separated tail estimate assembled from eventual p-series zero data. -/
noncomputable def profiledTailEstimate
    (zeroData : SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData) :
    SchwartzRiemannWeilProfiledSeparatedTailEstimate
      zeroData.exhaustion zeroData.system :=
  SchwartzRiemannWeilProfiledSeparatedTailEstimate.ofShellDecayAndCounting
    zeroData.shellDecay zeroData.counting zeroData.counting_cutoff_eq
    zeroData.growth_add_one_lt_decay

/-- The zero side generated by the eventual p-series envelope estimate. -/
noncomputable def zeroSide
    (zeroData : SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData) :
    SchwartzRiemannWeilZeroSide :=
  zeroData.profiledTailEstimate.toZeroSide

/-- The generated zero side uses the candidate extension-system weight. -/
theorem zeroSide_weight
    (zeroData : SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData)
    (f : SchwartzLineTestFunction)
    (rho : ZetaZeroSubtype) :
    zeroData.zeroSide.weight f rho = zeroData.system.weight f rho :=
  zeroData.profiledTailEstimate.toZeroSide_weight f rho

/-- Compact-exhaustion sums converge for the generated zero side. -/
theorem tendsto_windowZeroSide
    (zeroData : SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData)
    (windowExhaustion : ComplexCompactExhaustion)
    (f : SchwartzLineTestFunction) :
    Tendsto
      (fun n : Nat => zeroData.zeroSide.windowZeroSide windowExhaustion n f)
      atTop (nhds (zeroData.zeroSide.zeroSide f)) :=
  zeroData.profiledTailEstimate.tendsto_windowZeroSide windowExhaustion f

end SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData

/-- Formula identity data relative to eventual p-series envelope zero data. -/
structure SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaData
    (zeroData : SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData) where
  formulaData :
    SchwartzRiemannWeilFormulaIdentityData zeroData.zeroSide

namespace SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaData

/-- Build eventual formula data directly from raw formula sides. -/
noncomputable def ofRawSides
    {zeroData : SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData}
    (primeSide poleSide gammaSide : SchwartzLineTestFunction -> Real)
    (explicitFormula :
      forall f : SchwartzLineTestFunction,
        zeroData.zeroSide.zeroSide f =
          primeSide f + poleSide f + gammaSide f) :
    SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaData zeroData where
  formulaData :=
    SchwartzRiemannWeilFormulaIdentityData.ofRawSides
      primeSide poleSide gammaSide explicitFormula

/-- Compact-exhaustion sums converge to the formula-side residual expression. -/
theorem tendsto_windowZeroSide_formulaResidualSide
    {zeroData : SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData}
    (formulaData :
      SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaData zeroData)
    (windowExhaustion : ComplexCompactExhaustion)
    (f : SchwartzLineTestFunction) :
    Tendsto
      (fun n : Nat => zeroData.zeroSide.windowZeroSide windowExhaustion n f)
      atTop (nhds (formulaData.formulaData.sideData.residualSide f)) := by
  rw [← formulaData.formulaData.explicitFormula f]
  exact zeroData.tendsto_windowZeroSide windowExhaustion f

end SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaData

/-- Formula-side residual positivity relative to eventual p-series formula data. -/
structure SchwartzRiemannWeilEventualPSeriesEnvelopeResidualPositivityData
    {zeroData : SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData}
    (formulaData :
      SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaData zeroData) where
  formulaResidualData :
    SchwartzRiemannWeilFormulaResidualPositivityData formulaData.formulaData

namespace SchwartzRiemannWeilEventualPSeriesEnvelopeResidualPositivityData

/-- Build eventual residual positivity directly from raw residual-side data. -/
noncomputable def ofRawResidualPositivity
    {zeroData : SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData}
    {formulaData :
      SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaData zeroData}
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= formulaData.formulaData.sideData.residualSide f)
    (residual_positivity_implies_RHOn_univ :
      (forall f : SchwartzLineTestFunction,
        0 <= formulaData.formulaData.sideData.residualSide f) ->
        RHOn (fun _ : Complex => True)) :
    SchwartzRiemannWeilEventualPSeriesEnvelopeResidualPositivityData
      formulaData where
  formulaResidualData :=
    SchwartzRiemannWeilFormulaResidualPositivityData.ofRawResidualPositivity
      residual_nonneg residual_positivity_implies_RHOn_univ

/-- The packaged formula residual side is nonnegative. -/
theorem formulaResidual_nonneg
    {zeroData : SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData}
    {formulaData :
      SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilEventualPSeriesEnvelopeResidualPositivityData
        formulaData)
    (f : SchwartzLineTestFunction) :
    0 <= formulaData.formulaData.sideData.residualSide f :=
  positivityData.formulaResidualData.residual_nonneg f

/-- Formula-side residual positivity proves universal local RH. -/
theorem formulaResidual_positivity_implies_RHOn_univ
    {zeroData : SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData}
    {formulaData :
      SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilEventualPSeriesEnvelopeResidualPositivityData
        formulaData) :
    (forall f : SchwartzLineTestFunction,
      0 <= formulaData.formulaData.sideData.residualSide f) ->
      RHOn (fun _ : Complex => True) :=
  positivityData.formulaResidualData.residual_positivity_implies_RHOn_univ

end SchwartzRiemannWeilEventualPSeriesEnvelopeResidualPositivityData

/--
The combined eventual p-series envelope work package for the profiled
Riemann-Weil route.
-/
structure SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaResidualInputData where
  zeroData : SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData
  formulaData :
    SchwartzRiemannWeilFormulaIdentityData zeroData.zeroSide
  formulaResidualData :
    SchwartzRiemannWeilFormulaResidualPositivityData formulaData

namespace SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaResidualInputData

/-- Build the combined package from the split eventual work packages. -/
noncomputable def ofWorkPackages
    {zeroData : SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData}
    {formulaData :
      SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilEventualPSeriesEnvelopeResidualPositivityData
        formulaData) :
    SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaResidualInputData where
  zeroData := zeroData
  formulaData := formulaData.formulaData
  formulaResidualData := positivityData.formulaResidualData

/--
Build the full eventual p-series endpoint from any eventual p-series zero-data
package, raw formula sides, and raw residual positivity.
-/
noncomputable def ofZeroDataAndRawFormulaResidual
    (zeroData : SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData)
    (primeSide poleSide gammaSide : SchwartzLineTestFunction -> Real)
    (explicitFormula :
      forall f : SchwartzLineTestFunction,
        zeroData.zeroSide.zeroSide f =
          primeSide f + poleSide f + gammaSide f)
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= primeSide f + poleSide f + gammaSide f)
    (residual_positivity_implies_RHOn_univ :
      (forall f : SchwartzLineTestFunction,
        0 <= primeSide f + poleSide f + gammaSide f) ->
        RHOn (fun _ : Complex => True)) :
    SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaResidualInputData := by
  let formulaData :
      SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaData zeroData :=
    SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaData.ofRawSides
      primeSide poleSide gammaSide explicitFormula
  let positivityData :
      SchwartzRiemannWeilEventualPSeriesEnvelopeResidualPositivityData
        formulaData :=
    { formulaResidualData :=
        { residual_nonneg := fun f => by
            change 0 <= primeSide f + poleSide f + gammaSide f
            exact residual_nonneg f
          residual_positivity_implies_RHOn_univ := fun hres =>
            residual_positivity_implies_RHOn_univ <| fun f => by
              have hf := hres f
              change 0 <= primeSide f + poleSide f + gammaSide f at hf
              exact hf } }
  exact ofWorkPackages positivityData

/--
Build the full eventual p-series endpoint from exact polynomial shell counting,
an eventual envelope bound, raw formula sides, and raw residual positivity.
-/
noncomputable def ofExactShellCardAndRawFormulaResidual
    {exhaustion : ComplexCompactExhaustion}
    {system : SchwartzRiemannWeilExtensionSystem}
    (growthBound : SchwartzRiemannWeilExtensionGrowthBound system)
    (cutoff : Nat)
    (prefixBound : SchwartzLineTestFunction -> Nat -> Real)
    (zeroConstant : SchwartzLineTestFunction -> Real)
    (decayExponent : SchwartzLineTestFunction -> Real)
    (shellCardConstant growth : Real)
    (zeroConstant_nonneg :
      forall f : SchwartzLineTestFunction, 0 <= zeroConstant f)
    (prefixBound_nonneg :
      forall (f : SchwartzLineTestFunction) (n : Nat), 0 <= prefixBound f n)
    (pseriesBound_nonneg :
      forall (f : SchwartzLineTestFunction) (n : Nat),
        0 <= zeroConstant f *
          (1 / |(n : Real) + 1| ^ decayExponent f))
    (shellCardConstant_nonneg : 0 <= shellCardConstant)
    (tail_shellCard_le :
      forall n : Nat,
        ((exhaustion.zetaZeroFirstEntryShell (n + cutoff)).card : Real) <=
          shellCardConstant * |(n : Real) + 1| ^ growth)
    (envelope_zeroArgument_le_eventualPSeries :
      forall (f : SchwartzLineTestFunction) (rho : ZetaZeroSubtype),
        growthBound.envelope f (riemannWeilZeroArgument (rho : Complex)) <=
          SchwartzRiemannWeilExtensionShellDecayEstimate.eventualPSeriesShellBound
            cutoff prefixBound zeroConstant decayExponent f
            (exhaustion.zetaZeroFirstEntryIndex rho))
    (growth_add_one_lt_decay :
      forall f : SchwartzLineTestFunction, growth + 1 < decayExponent f)
    (primeSide poleSide gammaSide : SchwartzLineTestFunction -> Real)
    (explicitFormula :
      forall f : SchwartzLineTestFunction,
        (SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData.ofExactShellCardAndEventualPSeriesEnvelopeBound
            growthBound cutoff prefixBound zeroConstant decayExponent
            shellCardConstant growth zeroConstant_nonneg prefixBound_nonneg
            pseriesBound_nonneg shellCardConstant_nonneg tail_shellCard_le
            envelope_zeroArgument_le_eventualPSeries
            growth_add_one_lt_decay).zeroSide.zeroSide f =
          primeSide f + poleSide f + gammaSide f)
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= primeSide f + poleSide f + gammaSide f)
    (residual_positivity_implies_RHOn_univ :
      (forall f : SchwartzLineTestFunction,
        0 <= primeSide f + poleSide f + gammaSide f) ->
        RHOn (fun _ : Complex => True)) :
    SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaResidualInputData := by
  let zeroData :=
    SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData.ofExactShellCardAndEventualPSeriesEnvelopeBound
        growthBound cutoff prefixBound zeroConstant decayExponent
        shellCardConstant growth zeroConstant_nonneg prefixBound_nonneg
        pseriesBound_nonneg shellCardConstant_nonneg tail_shellCard_le
        envelope_zeroArgument_le_eventualPSeries
        growth_add_one_lt_decay
  let formulaData :
      SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaData zeroData :=
    SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaData.ofRawSides
      primeSide poleSide gammaSide explicitFormula
  let positivityData :
      SchwartzRiemannWeilEventualPSeriesEnvelopeResidualPositivityData
        formulaData :=
    { formulaResidualData :=
        { residual_nonneg := fun f => by
            change 0 <= primeSide f + poleSide f + gammaSide f
            exact residual_nonneg f
          residual_positivity_implies_RHOn_univ := fun hres =>
            residual_positivity_implies_RHOn_univ <| fun f => by
              have hf := hres f
              change 0 <= primeSide f + poleSide f + gammaSide f at hf
              exact hf } }
  exact ofWorkPackages positivityData

/--
Build the full eventual p-series endpoint from uniformly bounded tail shell
counts, an eventual envelope bound, raw formula sides, and raw residual
positivity.
-/
noncomputable def ofUniformTailShellCardAndRawFormulaResidual
    {exhaustion : ComplexCompactExhaustion}
    {system : SchwartzRiemannWeilExtensionSystem}
    (growthBound : SchwartzRiemannWeilExtensionGrowthBound system)
    (cutoff : Nat)
    (prefixBound : SchwartzLineTestFunction -> Nat -> Real)
    (zeroConstant : SchwartzLineTestFunction -> Real)
    (decayExponent : SchwartzLineTestFunction -> Real)
    (shellCardConstant : Real)
    (zeroConstant_nonneg :
      forall f : SchwartzLineTestFunction, 0 <= zeroConstant f)
    (prefixBound_nonneg :
      forall (f : SchwartzLineTestFunction) (n : Nat), 0 <= prefixBound f n)
    (pseriesBound_nonneg :
      forall (f : SchwartzLineTestFunction) (n : Nat),
        0 <= zeroConstant f *
          (1 / |(n : Real) + 1| ^ decayExponent f))
    (shellCardConstant_nonneg : 0 <= shellCardConstant)
    (tail_shellCard_le :
      forall n : Nat,
        ((exhaustion.zetaZeroFirstEntryShell (n + cutoff)).card : Real) <=
          shellCardConstant)
    (envelope_zeroArgument_le_eventualPSeries :
      forall (f : SchwartzLineTestFunction) (rho : ZetaZeroSubtype),
        growthBound.envelope f (riemannWeilZeroArgument (rho : Complex)) <=
          SchwartzRiemannWeilExtensionShellDecayEstimate.eventualPSeriesShellBound
            cutoff prefixBound zeroConstant decayExponent f
            (exhaustion.zetaZeroFirstEntryIndex rho))
    (growth_add_one_lt_decay :
      forall f : SchwartzLineTestFunction, (0 : Real) + 1 < decayExponent f)
    (primeSide poleSide gammaSide : SchwartzLineTestFunction -> Real)
    (explicitFormula :
      forall f : SchwartzLineTestFunction,
        (SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData.ofUniformTailShellCardAndEventualPSeriesEnvelopeBound
            growthBound cutoff prefixBound zeroConstant decayExponent
            shellCardConstant zeroConstant_nonneg prefixBound_nonneg
            pseriesBound_nonneg shellCardConstant_nonneg tail_shellCard_le
            envelope_zeroArgument_le_eventualPSeries
            growth_add_one_lt_decay).zeroSide.zeroSide f =
          primeSide f + poleSide f + gammaSide f)
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= primeSide f + poleSide f + gammaSide f)
    (residual_positivity_implies_RHOn_univ :
      (forall f : SchwartzLineTestFunction,
        0 <= primeSide f + poleSide f + gammaSide f) ->
        RHOn (fun _ : Complex => True)) :
    SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaResidualInputData := by
  let zeroData :=
    SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData.ofUniformTailShellCardAndEventualPSeriesEnvelopeBound
        growthBound cutoff prefixBound zeroConstant decayExponent
        shellCardConstant zeroConstant_nonneg prefixBound_nonneg
        pseriesBound_nonneg shellCardConstant_nonneg tail_shellCard_le
        envelope_zeroArgument_le_eventualPSeries
        growth_add_one_lt_decay
  let formulaData :
      SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaData zeroData :=
    SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaData.ofRawSides
      primeSide poleSide gammaSide explicitFormula
  let positivityData :
      SchwartzRiemannWeilEventualPSeriesEnvelopeResidualPositivityData
        formulaData :=
    { formulaResidualData :=
        { residual_nonneg := fun f => by
            change 0 <= primeSide f + poleSide f + gammaSide f
            exact residual_nonneg f
          residual_positivity_implies_RHOn_univ := fun hres =>
            residual_positivity_implies_RHOn_univ <| fun f => by
              have hf := hres f
              change 0 <= primeSide f + poleSide f + gammaSide f at hf
              exact hf } }
  exact ofWorkPackages positivityData

/--
Build the full eventual p-series endpoint from polynomial cumulative window
zero counting, an eventual envelope bound, raw formula sides, and raw residual
positivity.
-/
noncomputable def ofWindowCardAndRawFormulaResidual
    {exhaustion : ComplexCompactExhaustion}
    {system : SchwartzRiemannWeilExtensionSystem}
    (growthBound : SchwartzRiemannWeilExtensionGrowthBound system)
    (cutoff : Nat)
    (prefixBound : SchwartzLineTestFunction -> Nat -> Real)
    (zeroConstant : SchwartzLineTestFunction -> Real)
    (decayExponent : SchwartzLineTestFunction -> Real)
    (shellCardConstant growth : Real)
    (zeroConstant_nonneg :
      forall f : SchwartzLineTestFunction, 0 <= zeroConstant f)
    (prefixBound_nonneg :
      forall (f : SchwartzLineTestFunction) (n : Nat), 0 <= prefixBound f n)
    (pseriesBound_nonneg :
      forall (f : SchwartzLineTestFunction) (n : Nat),
        0 <= zeroConstant f *
          (1 / |(n : Real) + 1| ^ decayExponent f))
    (shellCardConstant_nonneg : 0 <= shellCardConstant)
    (tail_windowCard_le :
      forall n : Nat,
        ((exhaustion.zetaZeroSubtypeFinset (n + cutoff)).card : Real) <=
          shellCardConstant * |(n : Real) + 1| ^ growth)
    (envelope_zeroArgument_le_eventualPSeries :
      forall (f : SchwartzLineTestFunction) (rho : ZetaZeroSubtype),
        growthBound.envelope f (riemannWeilZeroArgument (rho : Complex)) <=
          SchwartzRiemannWeilExtensionShellDecayEstimate.eventualPSeriesShellBound
            cutoff prefixBound zeroConstant decayExponent f
            (exhaustion.zetaZeroFirstEntryIndex rho))
    (growth_add_one_lt_decay :
      forall f : SchwartzLineTestFunction, growth + 1 < decayExponent f)
    (primeSide poleSide gammaSide : SchwartzLineTestFunction -> Real)
    (explicitFormula :
      forall f : SchwartzLineTestFunction,
        (SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData.ofWindowCardAndEventualPSeriesEnvelopeBound
            growthBound cutoff prefixBound zeroConstant decayExponent
            shellCardConstant growth zeroConstant_nonneg prefixBound_nonneg
            pseriesBound_nonneg shellCardConstant_nonneg tail_windowCard_le
            envelope_zeroArgument_le_eventualPSeries
            growth_add_one_lt_decay).zeroSide.zeroSide f =
          primeSide f + poleSide f + gammaSide f)
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= primeSide f + poleSide f + gammaSide f)
    (residual_positivity_implies_RHOn_univ :
      (forall f : SchwartzLineTestFunction,
        0 <= primeSide f + poleSide f + gammaSide f) ->
        RHOn (fun _ : Complex => True)) :
    SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaResidualInputData := by
  let zeroData :=
    SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData.ofWindowCardAndEventualPSeriesEnvelopeBound
        growthBound cutoff prefixBound zeroConstant decayExponent
        shellCardConstant growth zeroConstant_nonneg prefixBound_nonneg
        pseriesBound_nonneg shellCardConstant_nonneg tail_windowCard_le
        envelope_zeroArgument_le_eventualPSeries
        growth_add_one_lt_decay
  exact ofZeroDataAndRawFormulaResidual zeroData primeSide poleSide gammaSide
    explicitFormula residual_nonneg residual_positivity_implies_RHOn_univ

/--
Build the full eventual p-series endpoint from uniformly bounded cumulative
window zero counts, an eventual envelope bound, raw formula sides, and raw
residual positivity.
-/
noncomputable def ofUniformTailWindowCardAndRawFormulaResidual
    {exhaustion : ComplexCompactExhaustion}
    {system : SchwartzRiemannWeilExtensionSystem}
    (growthBound : SchwartzRiemannWeilExtensionGrowthBound system)
    (cutoff : Nat)
    (prefixBound : SchwartzLineTestFunction -> Nat -> Real)
    (zeroConstant : SchwartzLineTestFunction -> Real)
    (decayExponent : SchwartzLineTestFunction -> Real)
    (shellCardConstant : Real)
    (zeroConstant_nonneg :
      forall f : SchwartzLineTestFunction, 0 <= zeroConstant f)
    (prefixBound_nonneg :
      forall (f : SchwartzLineTestFunction) (n : Nat), 0 <= prefixBound f n)
    (pseriesBound_nonneg :
      forall (f : SchwartzLineTestFunction) (n : Nat),
        0 <= zeroConstant f *
          (1 / |(n : Real) + 1| ^ decayExponent f))
    (shellCardConstant_nonneg : 0 <= shellCardConstant)
    (tail_windowCard_le :
      forall n : Nat,
        ((exhaustion.zetaZeroSubtypeFinset (n + cutoff)).card : Real) <=
          shellCardConstant)
    (envelope_zeroArgument_le_eventualPSeries :
      forall (f : SchwartzLineTestFunction) (rho : ZetaZeroSubtype),
        growthBound.envelope f (riemannWeilZeroArgument (rho : Complex)) <=
          SchwartzRiemannWeilExtensionShellDecayEstimate.eventualPSeriesShellBound
            cutoff prefixBound zeroConstant decayExponent f
            (exhaustion.zetaZeroFirstEntryIndex rho))
    (growth_add_one_lt_decay :
      forall f : SchwartzLineTestFunction, (0 : Real) + 1 < decayExponent f)
    (primeSide poleSide gammaSide : SchwartzLineTestFunction -> Real)
    (explicitFormula :
      forall f : SchwartzLineTestFunction,
        (SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData.ofUniformTailWindowCardAndEventualPSeriesEnvelopeBound
            growthBound cutoff prefixBound zeroConstant decayExponent
            shellCardConstant zeroConstant_nonneg prefixBound_nonneg
            pseriesBound_nonneg shellCardConstant_nonneg tail_windowCard_le
            envelope_zeroArgument_le_eventualPSeries
            growth_add_one_lt_decay).zeroSide.zeroSide f =
          primeSide f + poleSide f + gammaSide f)
    (residual_nonneg :
      forall f : SchwartzLineTestFunction,
        0 <= primeSide f + poleSide f + gammaSide f)
    (residual_positivity_implies_RHOn_univ :
      (forall f : SchwartzLineTestFunction,
        0 <= primeSide f + poleSide f + gammaSide f) ->
        RHOn (fun _ : Complex => True)) :
    SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaResidualInputData := by
  let zeroData :=
    SchwartzRiemannWeilEventualPSeriesEnvelopeZeroData.ofUniformTailWindowCardAndEventualPSeriesEnvelopeBound
        growthBound cutoff prefixBound zeroConstant decayExponent
        shellCardConstant zeroConstant_nonneg prefixBound_nonneg
        pseriesBound_nonneg shellCardConstant_nonneg tail_windowCard_le
        envelope_zeroArgument_le_eventualPSeries
        growth_add_one_lt_decay
  exact ofZeroDataAndRawFormulaResidual zeroData primeSide poleSide gammaSide
    explicitFormula residual_nonneg residual_positivity_implies_RHOn_univ

/-- Extract the formula-data package from the compact eventual target. -/
noncomputable def toFormulaDataPackage
    (data :
      SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaResidualInputData) :
    SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaData data.zeroData where
  formulaData := data.formulaData

/-- Extract the residual-positivity package from the compact eventual target. -/
noncomputable def toResidualPositivityDataPackage
    (data :
      SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaResidualInputData) :
    SchwartzRiemannWeilEventualPSeriesEnvelopeResidualPositivityData
      data.toFormulaDataPackage where
  formulaResidualData := data.formulaResidualData

/-- Convert the eventual p-series package to the preferred final endpoint. -/
noncomputable def toProfiledShellFormulaResidualInputData
    (data :
      SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaResidualInputData) :
    SchwartzRiemannWeilProfiledShellFormulaResidualInputData where
  exhaustion := data.zeroData.exhaustion
  system := data.zeroData.system
  shellDecay := data.zeroData.shellDecay
  counting := data.zeroData.counting
  cutoff_eq := data.zeroData.counting_cutoff_eq
  growth_add_one_lt_decay := data.zeroData.growth_add_one_lt_decay
  formulaData := data.formulaData
  formulaResidualData := data.formulaResidualData

/-- Assemble the eventual p-series package into the profiled certificate. -/
noncomputable def toProfiledTailCertificateData
    (data :
      SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaResidualInputData) :
    SchwartzRiemannWeilProfiledTailCertificateData :=
  data.toProfiledShellFormulaResidualInputData.toProfiledTailCertificateData

/-- The eventual p-series package proves universal local RH. -/
theorem RHOn_univ
    (data :
      SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaResidualInputData) :
    RHOn (fun _ : Complex => True) :=
  data.toProfiledShellFormulaResidualInputData.RHOn_univ

/-- The eventual p-series package proves the project-local RH statement. -/
theorem RHStatement
    (data :
      SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaResidualInputData) :
    RiemannHypothesisProject.RHStatement :=
  data.toProfiledShellFormulaResidualInputData.RHStatement

/-- The eventual p-series package proves Mathlib's `RiemannHypothesis`. -/
theorem mathlib_RH
    (data :
      SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaResidualInputData) :
    RiemannHypothesis :=
  data.toProfiledShellFormulaResidualInputData.mathlib_RH

/-- The eventual package's zero side is the packaged formula residual side. -/
theorem zeroSide_eq_formulaResidualSide
    (data :
      SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaResidualInputData)
    (f : SchwartzLineTestFunction) :
    data.toProfiledTailCertificateData.zeroSide.zeroSide f =
      data.formulaData.sideData.residualSide f :=
  (data.toProfiledShellFormulaResidualInputData).zeroSide_eq_formulaResidualSide f

/-- The eventual package's quadratic form is the packaged formula residual side. -/
theorem quadraticForm_eq_formulaResidualSide
    (data :
      SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaResidualInputData)
    (f : SchwartzLineTestFunction) :
    data.toProfiledTailCertificateData.quadraticForm f =
      data.formulaData.sideData.residualSide f :=
  (data.toProfiledShellFormulaResidualInputData).quadraticForm_eq_formulaResidualSide f

/-- Window zero-side sums converge to the packaged formula residual side. -/
theorem tendsto_windowZeroSide_formulaResidualSide
    (data :
      SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaResidualInputData)
    (windowExhaustion : ComplexCompactExhaustion)
    (f : SchwartzLineTestFunction) :
    Tendsto
      (fun n : Nat =>
        data.toProfiledTailCertificateData.zeroSide.windowZeroSide
          windowExhaustion n f)
      atTop (nhds (data.formulaData.sideData.residualSide f)) :=
  (data.toProfiledShellFormulaResidualInputData).tendsto_windowZeroSide_formulaResidualSide
    windowExhaustion f

end SchwartzRiemannWeilEventualPSeriesEnvelopeFormulaResidualInputData

/--
The combined cutoff-zero p-series envelope work package for the profiled
Riemann-Weil route.

This compact record keeps the zero, formula, and residual-positivity
obligations together. The split packages above are the preferred units for
working on the obligations independently.
-/
structure SchwartzRiemannWeilPSeriesEnvelopeFormulaResidualInputData where
  exhaustion : ComplexCompactExhaustion
  system : SchwartzRiemannWeilExtensionSystem
  growthBound : SchwartzRiemannWeilExtensionGrowthBound system
  zeroConstant : SchwartzLineTestFunction -> Real
  decayExponent : SchwartzLineTestFunction -> Real
  zeroConstant_nonneg :
    forall f : SchwartzLineTestFunction, 0 <= zeroConstant f
  pseriesBound_nonneg :
    forall (f : SchwartzLineTestFunction) (n : Nat),
      0 <= zeroConstant f *
        (1 / |(n : Real) + 1| ^ decayExponent f)
  envelope_zeroArgument_le_pseries :
    forall (f : SchwartzLineTestFunction) (rho : ZetaZeroSubtype),
      growthBound.envelope f (riemannWeilZeroArgument (rho : Complex)) <=
        zeroConstant f *
          (1 /
            |(exhaustion.zetaZeroFirstEntryIndex rho : Real) + 1| ^
              decayExponent f)
  counting : SchwartzRiemannWeilPolynomialZeroCountingEstimate exhaustion
  counting_cutoff_eq_zero : counting.cutoff = 0
  growth_add_one_lt_decay :
    forall f : SchwartzLineTestFunction,
      counting.growth + 1 < decayExponent f
  formulaData :
    SchwartzRiemannWeilFormulaIdentityData
      (SchwartzRiemannWeilProfiledShellFormulaResidualInputData.profiledTailEstimateOfGlobalPSeriesEnvelopeAndCounting
          growthBound zeroConstant decayExponent zeroConstant_nonneg
          pseriesBound_nonneg envelope_zeroArgument_le_pseries
          counting counting_cutoff_eq_zero growth_add_one_lt_decay).toZeroSide
  formulaResidualData :
    SchwartzRiemannWeilFormulaResidualPositivityData formulaData

namespace SchwartzRiemannWeilPSeriesEnvelopeFormulaResidualInputData

/-- Build the combined package from the split zero, formula, and residual packages. -/
noncomputable def ofWorkPackages
    {zeroData : SchwartzRiemannWeilPSeriesEnvelopeZeroData}
    {formulaData : SchwartzRiemannWeilPSeriesEnvelopeFormulaData zeroData}
    (positivityData :
      SchwartzRiemannWeilPSeriesEnvelopeResidualPositivityData formulaData) :
    SchwartzRiemannWeilPSeriesEnvelopeFormulaResidualInputData where
  exhaustion := zeroData.exhaustion
  system := zeroData.system
  growthBound := zeroData.growthBound
  zeroConstant := zeroData.zeroConstant
  decayExponent := zeroData.decayExponent
  zeroConstant_nonneg := zeroData.zeroConstant_nonneg
  pseriesBound_nonneg := zeroData.pseriesBound_nonneg
  envelope_zeroArgument_le_pseries :=
    zeroData.envelope_zeroArgument_le_pseries
  counting := zeroData.counting
  counting_cutoff_eq_zero := zeroData.counting_cutoff_eq_zero
  growth_add_one_lt_decay := zeroData.growth_add_one_lt_decay
  formulaData := formulaData.formulaData
  formulaResidualData := positivityData.formulaResidualData

/-- Extract the zero-data work package from the compact input target. -/
noncomputable def toZeroData
    (data : SchwartzRiemannWeilPSeriesEnvelopeFormulaResidualInputData) :
    SchwartzRiemannWeilPSeriesEnvelopeZeroData where
  exhaustion := data.exhaustion
  system := data.system
  growthBound := data.growthBound
  zeroConstant := data.zeroConstant
  decayExponent := data.decayExponent
  zeroConstant_nonneg := data.zeroConstant_nonneg
  pseriesBound_nonneg := data.pseriesBound_nonneg
  envelope_zeroArgument_le_pseries :=
    data.envelope_zeroArgument_le_pseries
  counting := data.counting
  counting_cutoff_eq_zero := data.counting_cutoff_eq_zero
  growth_add_one_lt_decay := data.growth_add_one_lt_decay

/-- Extract the formula-data work package from the compact input target. -/
noncomputable def toFormulaDataPackage
    (data : SchwartzRiemannWeilPSeriesEnvelopeFormulaResidualInputData) :
    SchwartzRiemannWeilPSeriesEnvelopeFormulaData data.toZeroData where
  formulaData := data.formulaData

/-- Extract the residual-positivity package from the compact input target. -/
noncomputable def toResidualPositivityDataPackage
    (data : SchwartzRiemannWeilPSeriesEnvelopeFormulaResidualInputData) :
    SchwartzRiemannWeilPSeriesEnvelopeResidualPositivityData
      data.toFormulaDataPackage where
  formulaResidualData := data.formulaResidualData

/-- Convert the p-series envelope package to the preferred final endpoint. -/
noncomputable def toProfiledShellFormulaResidualInputData
    (data : SchwartzRiemannWeilPSeriesEnvelopeFormulaResidualInputData) :
    SchwartzRiemannWeilProfiledShellFormulaResidualInputData :=
  SchwartzRiemannWeilProfiledShellFormulaResidualInputData.ofGlobalPSeriesEnvelopeAndCountingAndFormulaResidualPositivity
    data.growthBound data.zeroConstant data.decayExponent
    data.zeroConstant_nonneg data.pseriesBound_nonneg
    data.envelope_zeroArgument_le_pseries data.counting
    data.counting_cutoff_eq_zero data.growth_add_one_lt_decay
    data.formulaData data.formulaResidualData

/-- The shell-decay data assembled from the p-series envelope package. -/
noncomputable def shellDecay
    (data : SchwartzRiemannWeilPSeriesEnvelopeFormulaResidualInputData) :
    SchwartzRiemannWeilExtensionShellDecayEstimate
      data.exhaustion data.system :=
  SchwartzRiemannWeilProfiledShellFormulaResidualInputData.shellDecayOfGlobalPSeriesEnvelopeBound
    data.growthBound data.zeroConstant data.decayExponent
    data.zeroConstant_nonneg data.pseriesBound_nonneg
    data.envelope_zeroArgument_le_pseries

/-- The profiled separated tail estimate assembled from the package. -/
noncomputable def profiledTailEstimate
    (data : SchwartzRiemannWeilPSeriesEnvelopeFormulaResidualInputData) :
    SchwartzRiemannWeilProfiledSeparatedTailEstimate
      data.exhaustion data.system :=
  SchwartzRiemannWeilProfiledShellFormulaResidualInputData.profiledTailEstimateOfGlobalPSeriesEnvelopeAndCounting
    data.growthBound data.zeroConstant data.decayExponent
    data.zeroConstant_nonneg data.pseriesBound_nonneg
    data.envelope_zeroArgument_le_pseries data.counting
    data.counting_cutoff_eq_zero data.growth_add_one_lt_decay

/-- Export the formula identity data in the package. -/
noncomputable def toFormulaIdentityData
    (data : SchwartzRiemannWeilPSeriesEnvelopeFormulaResidualInputData) :
    SchwartzRiemannWeilFormulaIdentityData
      data.profiledTailEstimate.toZeroSide :=
  data.formulaData

/-- Export formula-side residual positivity. -/
noncomputable def toFormulaResidualPositivityData
    (data : SchwartzRiemannWeilPSeriesEnvelopeFormulaResidualInputData) :
    SchwartzRiemannWeilFormulaResidualPositivityData data.formulaData :=
  data.formulaResidualData

/-- Assemble the p-series envelope package into the profiled certificate. -/
noncomputable def toProfiledTailCertificateData
    (data : SchwartzRiemannWeilPSeriesEnvelopeFormulaResidualInputData) :
    SchwartzRiemannWeilProfiledTailCertificateData :=
  data.toProfiledShellFormulaResidualInputData.toProfiledTailCertificateData

/-- Assemble the p-series envelope package into the global criterion. -/
noncomputable def toGlobalCriterion
    (data : SchwartzRiemannWeilPSeriesEnvelopeFormulaResidualInputData) :
    SchwartzRiemannWeilGlobalCriterion :=
  data.toProfiledShellFormulaResidualInputData.toGlobalCriterion

/-- The package's formula residual side is nonnegative. -/
theorem formulaResidual_nonneg
    (data : SchwartzRiemannWeilPSeriesEnvelopeFormulaResidualInputData)
    (f : SchwartzLineTestFunction) :
    0 <= data.formulaData.sideData.residualSide f :=
  data.formulaResidualData.residual_nonneg f

/-- The p-series envelope package proves universal local RH. -/
theorem RHOn_univ
    (data : SchwartzRiemannWeilPSeriesEnvelopeFormulaResidualInputData) :
    RHOn (fun _ : Complex => True) :=
  data.toProfiledShellFormulaResidualInputData.RHOn_univ

/-- The p-series envelope package proves the project-local RH statement. -/
theorem RHStatement
    (data : SchwartzRiemannWeilPSeriesEnvelopeFormulaResidualInputData) :
    RiemannHypothesisProject.RHStatement :=
  data.toProfiledShellFormulaResidualInputData.RHStatement

/-- The p-series envelope package proves Mathlib's `RiemannHypothesis`. -/
theorem mathlib_RH
    (data : SchwartzRiemannWeilPSeriesEnvelopeFormulaResidualInputData) :
    RiemannHypothesis :=
  data.toProfiledShellFormulaResidualInputData.mathlib_RH

/-- The package's zero side is the packaged formula residual side. -/
theorem zeroSide_eq_formulaResidualSide
    (data : SchwartzRiemannWeilPSeriesEnvelopeFormulaResidualInputData)
    (f : SchwartzLineTestFunction) :
    data.toProfiledTailCertificateData.zeroSide.zeroSide f =
      data.formulaData.sideData.residualSide f :=
  (data.toProfiledShellFormulaResidualInputData).zeroSide_eq_formulaResidualSide f

/-- The package's quadratic form is the packaged formula residual side. -/
theorem quadraticForm_eq_formulaResidualSide
    (data : SchwartzRiemannWeilPSeriesEnvelopeFormulaResidualInputData)
    (f : SchwartzLineTestFunction) :
    data.toProfiledTailCertificateData.quadraticForm f =
      data.formulaData.sideData.residualSide f :=
  (data.toProfiledShellFormulaResidualInputData).quadraticForm_eq_formulaResidualSide f

/-- Window zero-side sums converge to the packaged formula residual side. -/
theorem tendsto_windowZeroSide_formulaResidualSide
    (data : SchwartzRiemannWeilPSeriesEnvelopeFormulaResidualInputData)
    (windowExhaustion : ComplexCompactExhaustion)
    (f : SchwartzLineTestFunction) :
    Tendsto
      (fun n : Nat =>
        data.toProfiledTailCertificateData.zeroSide.windowZeroSide
          windowExhaustion n f)
      atTop (nhds (data.formulaData.sideData.residualSide f)) :=
  (data.toProfiledShellFormulaResidualInputData).tendsto_windowZeroSide_formulaResidualSide
    windowExhaustion f

end SchwartzRiemannWeilPSeriesEnvelopeFormulaResidualInputData

end RiemannHypothesisProject
