import RiemannHypothesisProject.LiCriterion.ZetaLiCoefficient
import RiemannHypothesisProject.RiemannVonMangoldt.RiemannXiJensen

/-!
# A1 zero-counting audit smoke checks

This audit-only file keeps the representative source, normalization, count,
dyadic, and downstream inverse-square declarations easy to recheck. The
semantic verdict and dependency trace live in the dated A1 report.
-/

#check AnalyticOnNhd.sum_divisor_le

#check RiemannHypothesisProject.ComplexCompactExhaustion.exists_riemannThetaTail_global_exp_bound
#check RiemannHypothesisProject.ComplexCompactExhaustion.completedRiemannZeta₀_eq_integral_Ioi
#check RiemannHypothesisProject.ComplexCompactExhaustion.exists_riemannXi_sphere_exp_mulLog_bound
#check RiemannHypothesisProject.ComplexCompactExhaustion.analyticOrderAt_riemannXi_eq_zetaZeroMultiplicity
#check RiemannHypothesisProject.ComplexCompactExhaustion.exists_riemannXi_jensen_mulLog_bound
#check RiemannHypothesisProject.ComplexCompactExhaustion.canonicalMultiplicityCount_le_riemannXi_divisor
#check RiemannHypothesisProject.ComplexCompactExhaustion.exists_unconditional_canonicalMultiplicityCount_mulLog_bound
#check RiemannHypothesisProject.ComplexCompactExhaustion.exists_unconditional_canonicalMultiplicityCount_dyadic_mulLog_bound
#check RiemannHypothesisProject.ComplexCompactExhaustion.unconditional_positiveOrdinateZetaZero_multiplicityHeightDecay_summable_of_mulLogCount
#check RiemannHypothesisProject.ComplexCompactExhaustion.unconditional_positiveOrdinateZetaZero_multiplicityClampedInverseSquare_summable
#check RiemannHypothesisProject.ComplexCompactExhaustion.summable_multiplicityWeightedZetaLiPairedSummand

#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.exists_riemannThetaTail_global_exp_bound
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.completedRiemannZeta₀_eq_integral_Ioi
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.exists_riemannXi_sphere_exp_mulLog_bound
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.analyticOrderAt_riemannXi_eq_zetaZeroMultiplicity
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.exists_riemannXi_jensen_mulLog_bound
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.canonicalMultiplicityCount_le_riemannXi_divisor
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.exists_unconditional_canonicalMultiplicityCount_mulLog_bound
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.exists_unconditional_canonicalMultiplicityCount_dyadic_mulLog_bound
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.unconditional_positiveOrdinateZetaZero_multiplicityHeightDecay_summable_of_mulLogCount
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.unconditional_positiveOrdinateZetaZero_multiplicityClampedInverseSquare_summable
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.summable_multiplicityWeightedZetaLiPairedSummand
