import RiemannHypothesisProject.GuinandWeilConcrete.MultiplicityPolynomialGaussianFormulaHandoff

/-!
# A2 p-series audit smoke checks

This audit-only file keeps the representative decay, multiplicity-growth,
normalization, all-zero summability, cutoff, and formula-handoff declarations
easy to recheck. The semantic verdict and dependency trace live in the dated
A2 report.
-/

#check RiemannHypothesisProject.exists_bound_norm_mul_shiftedRadius_pow_guinandWeilPiGaussianSource_horizontalStrip
#check RiemannHypothesisProject.exists_bound_norm_mul_shiftedRadius_pow_guinandWeilPiPolynomialGaussianSource_horizontalStrip
#check RiemannHypothesisProject.norm_guinandWeilPiPolynomialGaussianCompletedZetaZeroWeight_le_shiftedRadius

#check RiemannHypothesisProject.ComplexCompactExhaustion.riemannXiCanonicalMultiplicityPolynomialGrowth
#check RiemannHypothesisProject.ComplexCompactExhaustion.CanonicalMultiplicityPolynomialGrowth.exists_global_dyadic_bound
#check RiemannHypothesisProject.ComplexCompactExhaustion.zetaZeroMultiplicity_conj
#check RiemannHypothesisProject.ComplexCompactExhaustion.mem_closedBallZeroResidualRealAxisFinset_one_of_axis_not_trivial

#check RiemannHypothesisProject.ComplexCompactExhaustion.multiplicityPolynomialGaussianCompletedZetaZeroWeight_eq_indicator
#check RiemannHypothesisProject.ComplexCompactExhaustion.tsum_multiplicityPolynomialGaussianCompletedZetaZeroWeight_eq_nontrivial
#check RiemannHypothesisProject.ComplexCompactExhaustion.summable_norm_multiplicityPolynomialGaussianCompletedZetaZeroWeight_unconditional
#check RiemannHypothesisProject.ComplexCompactExhaustion.summable_multiplicityPolynomialGaussianCompletedZetaZeroWeight_unconditional
#check RiemannHypothesisProject.ComplexCompactExhaustion.tendsto_multiplicityPolynomialGaussianCompletedZetaZeroWindowSum_unconditional
#check RiemannHypothesisProject.ComplexCompactExhaustion.tendsto_tsum_norm_multiplicityPolynomialGaussianCompletedZetaZero_compl_unconditional

#check RiemannHypothesisProject.summable_norm_guinandWeilLiteraturePrimeTerm_guinandWeilPiPolynomialGaussianSchwartz
#check RiemannHypothesisProject.summable_norm_guinandWeilPiMultiplicityPolynomialGaussianLiteratureZeroWeight
#check RiemannHypothesisProject.tendsto_norm_guinandWeilPiMultiplicityPolynomialGaussianLiteratureZeroSide_sub_truncated
#check RiemannHypothesisProject.guinandWeilPiMultiplicityPolynomialGaussianLiteratureFormula_of_truncatedEventualErrorEnvelope

#print axioms RiemannHypothesisProject.exists_bound_norm_mul_shiftedRadius_pow_guinandWeilPiPolynomialGaussianSource_horizontalStrip
#print axioms RiemannHypothesisProject.norm_guinandWeilPiPolynomialGaussianCompletedZetaZeroWeight_le_shiftedRadius
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.riemannXiCanonicalMultiplicityPolynomialGrowth
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.CanonicalMultiplicityPolynomialGrowth.exists_global_dyadic_bound
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.zetaZeroMultiplicity_conj
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.mem_closedBallZeroResidualRealAxisFinset_one_of_axis_not_trivial
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.multiplicityPolynomialGaussianCompletedZetaZeroWeight_eq_indicator
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.summable_norm_multiplicityPolynomialGaussianCompletedZetaZeroWeight_unconditional
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.tendsto_multiplicityPolynomialGaussianCompletedZetaZeroWindowSum_unconditional
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.tendsto_tsum_norm_multiplicityPolynomialGaussianCompletedZetaZero_compl_unconditional
#print axioms RiemannHypothesisProject.summable_norm_guinandWeilLiteraturePrimeTerm_guinandWeilPiPolynomialGaussianSchwartz
#print axioms RiemannHypothesisProject.summable_norm_guinandWeilPiMultiplicityPolynomialGaussianLiteratureZeroWeight
#print axioms RiemannHypothesisProject.tendsto_norm_guinandWeilPiMultiplicityPolynomialGaussianLiteratureZeroSide_sub_truncated
#print axioms RiemannHypothesisProject.guinandWeilPiMultiplicityPolynomialGaussianLiteratureFormula_of_truncatedEventualErrorEnvelope
