import RiemannHypothesisProject.GuinandWeilConcrete.PolynomialGaussianDensityBridge

/-!
# A3 formula-identity audit smoke checks

This audit-only file keeps the representative contour, divisor,
good-height, right-vertical normalization, infinite-limit, and density-consumer
declarations easy to recheck. The semantic verdict and complete normalization
trace live in the dated A3 report.
-/

#check RiemannHypothesisProject.exists_pos_const_norm_guinandWeilXiContourWeight_horizontal_le
#check RiemannHypothesisProject.guinandWeilNormalizedRectangleIntegral_weight_mul_logDeriv_eq_sum
#check RiemannHypothesisProject.ComplexCompactExhaustion.analyticOrderAt_riemannXi_eq_zetaZeroMultiplicity_of_not_trivial
#check RiemannHypothesisProject.ComplexCompactExhaustion.guinandWeilXi_rectangleBoundary_decomposition_eq_weightedZeroSum

#check RiemannHypothesisProject.ComplexCompactExhaustion.exists_fixed_canonicalXi_goodHeight_logDeriv_bound
#check RiemannHypothesisProject.ComplexCompactExhaustion.exists_canonicalXi_goodHeight_both_horizontalIntegrals_tendsto_zero
#check RiemannHypothesisProject.ComplexCompactExhaustion.riemannXi_ne_zero_on_symmetric_goodHeight_rectangleBorder
#check RiemannHypothesisProject.ComplexCompactExhaustion.tendsto_re_riemannXiRectangleWeightedZeroSum

#check RiemannHypothesisProject.integral_guinandWeilPiPolynomialGaussianSource_horizontalLine_mul_exp_eq_fourier
#check RiemannHypothesisProject.integral_shiftedPolynomialGaussian_mul_vonMangoldtLSeries_eq_primeFourierTsum
#check RiemannHypothesisProject.neg_one_div_pi_mul_re_integral_xiContourWeight_vonMangoldtLSeries_right_eq_literaturePrime
#check RiemannHypothesisProject.one_div_pi_mul_re_integral_xiContourWeight_rational_right_eq_literaturePole
#check RiemannHypothesisProject.one_div_pi_mul_re_integral_xiContourWeight_archimedean_right_eq_literatureGamma
#check RiemannHypothesisProject.one_div_pi_mul_re_integral_xiContourWeight_logDeriv_riemannXi_right_eq_literatureResidual

#check RiemannHypothesisProject.ComplexCompactExhaustion.guinandWeilPiEvenPolynomialGaussianLiteratureFormula
#check RiemannHypothesisProject.denseRange_guinandWeilPiEvenPolynomialGaussianRealEvenLinearMap
#check RiemannHypothesisProject.exists_evenPolynomialGaussianLiteratureFormulaApproximation
#check RiemannHypothesisProject.exists_evenPolynomialGaussianZeroSide_tendsto_continuousResidual

#print axioms RiemannHypothesisProject.guinandWeilNormalizedRectangleIntegral_weight_mul_logDeriv_eq_sum
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.analyticOrderAt_riemannXi_eq_zetaZeroMultiplicity_of_not_trivial
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.guinandWeilXi_rectangleBoundary_decomposition_eq_weightedZeroSum
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.exists_canonicalXi_goodHeight_both_horizontalIntegrals_tendsto_zero
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.riemannXi_ne_zero_on_symmetric_goodHeight_rectangleBorder
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.tendsto_re_riemannXiRectangleWeightedZeroSum
#print axioms RiemannHypothesisProject.integral_shiftedPolynomialGaussian_mul_vonMangoldtLSeries_eq_primeFourierTsum
#print axioms RiemannHypothesisProject.neg_one_div_pi_mul_re_integral_xiContourWeight_vonMangoldtLSeries_right_eq_literaturePrime
#print axioms RiemannHypothesisProject.one_div_pi_mul_re_integral_xiContourWeight_rational_right_eq_literaturePole
#print axioms RiemannHypothesisProject.one_div_pi_mul_re_integral_xiContourWeight_archimedean_right_eq_literatureGamma
#print axioms RiemannHypothesisProject.one_div_pi_mul_re_integral_xiContourWeight_logDeriv_riemannXi_right_eq_literatureResidual
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.guinandWeilPiEvenPolynomialGaussianLiteratureFormula
#print axioms RiemannHypothesisProject.denseRange_guinandWeilPiEvenPolynomialGaussianRealEvenLinearMap
#print axioms RiemannHypothesisProject.exists_evenPolynomialGaussianLiteratureFormulaApproximation
#print axioms RiemannHypothesisProject.exists_evenPolynomialGaussianZeroSide_tendsto_continuousResidual
