import RiemannHypothesisProject.WeilPositivity.BurnolFormulaClosure

/-!
# A4 Burnol/formula-bridge finding smoke checks

This audit-only file checks the reopened M90 Burnol formula closure. The M80
polynomial-Gaussian verdict remains recorded by the completed A3 audit. These
M90 signatures expose the exact fixed-support prime/pole/Gamma residual,
Fourier normalization, source assumptions, and multiplicity-aware zero side.
-/

#check RiemannHypothesisProject.SchwartzLineTestFunction.burnolLocalSpectralQuadraticForm
#check RiemannHypothesisProject.SchwartzLineTestFunction.BurnolGuinandWeilSourceAssumptions
#check RiemannHypothesisProject.SchwartzLineTestFunction.guinandWeilLiteraturePrimeSide_fourierAutocorrelation_eq_zero
#check RiemannHypothesisProject.SchwartzLineTestFunction.integral_burnolPoleSpectralKernel_mul_fourierEnergyDensity_eq_poleSide
#check RiemannHypothesisProject.SchwartzLineTestFunction.two_pi_mul_guinandWeilLiteratureGammaSide_eq_burnolArchimedeanIntegral
#check RiemannHypothesisProject.SchwartzLineTestFunction.burnolLocalSpectralQuadraticForm_eq_two_pi_mul_guinandWeilBurnolLiteratureResidualSide
#check RiemannHypothesisProject.SchwartzLineTestFunction.burnolLocalSpectralQuadraticForm_eq_two_pi_mul_guinandWeilBurnolLiteratureZeroSide
#check RiemannHypothesisProject.SchwartzLineTestFunction.exists_burnolFixedSupport_guinandWeilBurnolLiteratureResidual_nonneg
#check RiemannHypothesisProject.SchwartzLineTestFunction.exists_burnolFixedSupport_guinandWeilBurnolLiteratureZeroSide_nonneg

#print axioms RiemannHypothesisProject.SchwartzLineTestFunction.burnolLocalSpectralQuadraticForm_eq_two_pi_mul_guinandWeilBurnolLiteratureResidualSide
#print axioms RiemannHypothesisProject.SchwartzLineTestFunction.burnolLocalSpectralQuadraticForm_eq_two_pi_mul_guinandWeilBurnolLiteratureZeroSide
#print axioms RiemannHypothesisProject.SchwartzLineTestFunction.exists_burnolFixedSupport_guinandWeilBurnolLiteratureResidual_nonneg
#print axioms RiemannHypothesisProject.SchwartzLineTestFunction.exists_burnolFixedSupport_guinandWeilBurnolLiteratureZeroSide_nonneg
