import RiemannHypothesisProject.GuinandWeilConcrete.UnconditionalMultiplicityPolynomialGaussianZeroSide
import RiemannHypothesisProject.GuinandWeilConcrete.MultiplicityPolynomialGaussianFormulaHandoff
import RiemannHypothesisProject.GuinandWeilConcrete.PolynomialGaussianFormulaIdentity
import RiemannHypothesisProject.GuinandWeilConcrete.PolynomialGaussianDensityBridge
import RiemannHypothesisProject.LiCriterion.ZetaBombieriLagariasCriterion
import RiemannHypothesisProject.LiCriterion.CutoffCovarianceUnconditional
import RiemannHypothesisProject.WeilPositivity.BurnolLocalSupportUnconditional

/-!
# Adversarial endpoint smoke audit

This file keeps representative completed-track declarations and their axiom
reports easy to recheck. It is audit-only and must not be imported by
production modules.
-/

#check RiemannHypothesisProject.ComplexCompactExhaustion.exists_unconditional_canonicalMultiplicityCount_mulLog_bound
#check RiemannHypothesisProject.ComplexCompactExhaustion.unconditional_positiveOrdinateZetaZero_multiplicityClampedInverseSquare_summable

#check RiemannHypothesisProject.ComplexCompactExhaustion.summable_norm_multiplicityPolynomialGaussianCompletedZetaZeroWeight_unconditional
#check RiemannHypothesisProject.ComplexCompactExhaustion.tendsto_multiplicityPolynomialGaussianCompletedZetaZeroWindowSum_unconditional
#check RiemannHypothesisProject.guinandWeilPiMultiplicityPolynomialGaussianLiteratureFormula_of_truncatedEventualErrorEnvelope

#check RiemannHypothesisProject.ComplexCompactExhaustion.guinandWeilPiEvenPolynomialGaussianLiteratureFormula
#check RiemannHypothesisProject.exists_evenPolynomialGaussianZeroSide_tendsto_continuousResidual

#check RiemannHypothesisProject.ComplexCompactExhaustion.RHStatement_iff_fullZetaLiCoefficient_nonneg
#check RiemannHypothesisProject.ComplexCompactExhaustion.mathlib_RH_iff_fullZetaLiCoefficient_nonneg
#check RiemannHypothesisProject.ComplexCompactExhaustion.tendsto_liCutoffCovariance_of_primeMomentAsymptotics
#check RiemannHypothesisProject.SchwartzLineTestFunction.exists_burnolFixedSupport_spectral_nonneg_of_binet
#check RiemannHypothesisProject.ComplexCompactExhaustion.bennettGammaBinetDigammaFormula
#check RiemannHypothesisProject.SchwartzLineTestFunction.exists_burnolFixedSupport_spectral_nonneg
#check RiemannHypothesisProject.ComplexCompactExhaustion.bombieriLagariasPrimeMomentAsymptotic
#check RiemannHypothesisProject.ComplexCompactExhaustion.tendsto_liCutoffCovariance_unconditional

#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.exists_unconditional_canonicalMultiplicityCount_mulLog_bound
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.summable_norm_multiplicityPolynomialGaussianCompletedZetaZeroWeight_unconditional
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.guinandWeilPiEvenPolynomialGaussianLiteratureFormula
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.RHStatement_iff_fullZetaLiCoefficient_nonneg
#print axioms RiemannHypothesisProject.SchwartzLineTestFunction.exists_burnolFixedSupport_spectral_nonneg_of_binet
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.bennettGammaBinetDigammaFormula
#print axioms RiemannHypothesisProject.SchwartzLineTestFunction.exists_burnolFixedSupport_spectral_nonneg
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.bombieriLagariasPrimeMomentAsymptotic
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.tendsto_liCutoffCovariance_unconditional
