import RiemannHypothesisProject.RiemannVonMangoldt.RiemannXiJensen
import RiemannHypothesisProject.GuinandWeilConcrete.MultiplicityPolynomialGaussianFormulaHandoff
import RiemannHypothesisProject.GuinandWeilConcrete.PolynomialGaussianDensityBridge
import RiemannHypothesisProject.LiCriterion.ZetaBombieriLagariasCriterion
import RiemannHypothesisProject.LiCriterion.CutoffCovarianceUnconditional
import RiemannHypothesisProject.WeilPositivity.ZetaPolynomialGaussianFormulaBridge
import RiemannHypothesisProject.WeilPositivity.BurnolFormulaClosure

/-!
# Publication endpoint axiom audit

Run with:

`lake env lean RELEASE/PublicationAxiomAudit.lean`

The output is preserved with each controlled release. This file imports
production endpoints, but no production module imports this audit file.
-/

#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.exists_unconditional_canonicalMultiplicityCount_mulLog_bound
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.unconditional_positiveOrdinateZetaZero_multiplicityClampedInverseSquare_summable
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.summable_norm_multiplicityPolynomialGaussianCompletedZetaZeroWeight_unconditional
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.guinandWeilPiEvenPolynomialGaussianLiteratureFormula
#print axioms RiemannHypothesisProject.exists_evenPolynomialGaussianZeroSide_tendsto_continuousResidual
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.RHStatement_iff_fullZetaLiCoefficient_nonneg
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.mathlib_RH_iff_fullZetaLiCoefficient_nonneg
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.zetaWeilPolynomialGaussian_formula_on_autocorrelation
#print axioms RiemannHypothesisProject.SchwartzLineTestFunction.exists_burnolFixedSupport_guinandWeilBurnolLiteratureResidual_nonneg
#print axioms RiemannHypothesisProject.SchwartzLineTestFunction.exists_burnolFixedSupport_guinandWeilBurnolLiteratureZeroSide_nonneg
#print axioms RiemannHypothesisProject.ComplexCompactExhaustion.tendsto_liCutoffCovariance_unconditional
